/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  CreatePaymentReqDTO,
  PaymentControllerCancelPayment200,
  PaymentControllerCreatePayment200,
  PaymentControllerGetPayment200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 티켓 상품 ID를 전달하면 결제 요청을 생성하고 REQUESTED 상태로 저장합니다.
 * @summary 결제 요청 생성
 */
export const paymentControllerCreatePayment = (
    createPaymentReqDTO: CreatePaymentReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentControllerCreatePayment200>(
      {url: `/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPaymentReqDTO, signal
    },
      options);
    }
  


export const getPaymentControllerCreatePaymentMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreatePayment>>, TError,{data: CreatePaymentReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreatePayment>>, TError,{data: CreatePaymentReqDTO}, TContext> => {

const mutationKey = ['paymentControllerCreatePayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerCreatePayment>>, {data: CreatePaymentReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  paymentControllerCreatePayment(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerCreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerCreatePayment>>>
    export type PaymentControllerCreatePaymentMutationBody = CreatePaymentReqDTO
    export type PaymentControllerCreatePaymentMutationError = CommonResponse

    /**
 * @summary 결제 요청 생성
 */
export const usePaymentControllerCreatePayment = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreatePayment>>, TError,{data: CreatePaymentReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerCreatePayment>>,
        TError,
        {data: CreatePaymentReqDTO},
        TContext
      > => {
      return useMutation(getPaymentControllerCreatePaymentMutationOptions(options), queryClient);
    }
    /**
 * 결제 복귀/새로고침 시 현재 결제 상태를 조회합니다. 본인의 결제만 조회할 수 있습니다.
 * @summary 결제 상태 조회
 */
export const paymentControllerGetPayment = (
    paymentId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentControllerGetPayment200>(
      {url: `/payments/${paymentId}`, method: 'GET', signal
    },
      options);
    }
  



export const getPaymentControllerGetPaymentQueryKey = (paymentId: number,) => {
    return [
    `/payments/${paymentId}`
    ] as const;
    }

    
export const getPaymentControllerGetPaymentQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError = CommonResponse>(paymentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetPaymentQueryKey(paymentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGetPayment>>> = ({ signal }) => paymentControllerGetPayment(paymentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(paymentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGetPayment>>>
export type PaymentControllerGetPaymentQueryError = CommonResponse


export function usePaymentControllerGetPayment<TData = Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError = CommonResponse>(
 paymentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetPayment>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetPayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetPayment<TData = Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError = CommonResponse>(
 paymentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetPayment>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetPayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetPayment<TData = Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError = CommonResponse>(
 paymentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 결제 상태 조회
 */

export function usePaymentControllerGetPayment<TData = Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError = CommonResponse>(
 paymentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetPaymentQueryOptions(paymentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * PayApp이 결제 완료 시 호출하는 webhook입니다. 인증 없이 수신하며, mulNo 기반으로 결제를 조회하여 상태를 갱신하고 티켓을 발급합니다. 멱등성이 보장됩니다.
 * @summary PayApp 결제 콜백(feedbackurl) 수신
 */
export const paymentControllerHandleWebhook = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/payments/webhook`, method: 'POST', signal
    },
      options);
    }
  


export const getPaymentControllerHandleWebhookMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerHandleWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerHandleWebhook>>, TError,void, TContext> => {

const mutationKey = ['paymentControllerHandleWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerHandleWebhook>>, void> = () => {
          

          return  paymentControllerHandleWebhook(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerHandleWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerHandleWebhook>>>
    
    export type PaymentControllerHandleWebhookMutationError = CommonResponse

    /**
 * @summary PayApp 결제 콜백(feedbackurl) 수신
 */
export const usePaymentControllerHandleWebhook = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerHandleWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerHandleWebhook>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPaymentControllerHandleWebhookMutationOptions(options), queryClient);
    }
    /**
 * 본인의 결제를 취소합니다. PAID 상태의 결제만 취소할 수 있습니다. 이미 취소된 결제는 멱등하게 처리됩니다.
 * @summary 결제 취소 요청
 */
export const paymentControllerCancelPayment = (
    paymentId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentControllerCancelPayment200>(
      {url: `/payments/${paymentId}/cancel`, method: 'POST', signal
    },
      options);
    }
  


export const getPaymentControllerCancelPaymentMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCancelPayment>>, TError,{paymentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCancelPayment>>, TError,{paymentId: number}, TContext> => {

const mutationKey = ['paymentControllerCancelPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerCancelPayment>>, {paymentId: number}> = (props) => {
          const {paymentId} = props ?? {};

          return  paymentControllerCancelPayment(paymentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerCancelPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerCancelPayment>>>
    
    export type PaymentControllerCancelPaymentMutationError = CommonResponse

    /**
 * @summary 결제 취소 요청
 */
export const usePaymentControllerCancelPayment = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCancelPayment>>, TError,{paymentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerCancelPayment>>,
        TError,
        {paymentId: number},
        TContext
      > => {
      return useMutation(getPaymentControllerCancelPaymentMutationOptions(options), queryClient);
    }
    