/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  InternalControllerGetHealth200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Verifies internal API key authentication and routing.
 * @summary Internal API health check
 */
export const internalControllerGetHealth = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerGetHealth200>(
      {url: `/api/v1/internal/health`, method: 'GET', signal
    },
      options);
    }
  



export const getInternalControllerGetHealthQueryKey = () => {
    return [
    `/api/v1/internal/health`
    ] as const;
    }

    
export const getInternalControllerGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalControllerGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalControllerGetHealth>>> = ({ signal }) => internalControllerGetHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalControllerGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof internalControllerGetHealth>>>
export type InternalControllerGetHealthQueryError = CommonResponse


export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal API health check
 */

export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalControllerGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




