/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  InternalControllerGetHealth200,
  InternalControllerGetInternalInsight200,
  InternalControllerGetInternalPortfolio200,
  InternalControllerSearchInternalInsights200,
  InternalControllerSearchInternalInsightsParams,
  InternalControllerUpdateInternalPortfolio200,
  UpdatePortfolioResultReqDTO
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Verifies internal API key authentication and routing.
 * @summary Internal API health check
 */
export const internalControllerGetHealth = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerGetHealth200>(
      {url: `/internal/health`, method: 'GET', signal
    },
      options);
    }
  



export const getInternalControllerGetHealthQueryKey = () => {
    return [
    `/internal/health`
    ] as const;
    }

    
export const getInternalControllerGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalControllerGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalControllerGetHealth>>> = ({ signal }) => internalControllerGetHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalControllerGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof internalControllerGetHealth>>>
export type InternalControllerGetHealthQueryError = CommonResponse


export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetHealth>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal API health check
 */

export function useInternalControllerGetHealth<TData = Awaited<ReturnType<typeof internalControllerGetHealth>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalControllerGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI 서버가 키워드 기반으로 사용자 인사이트를 벡터 검색합니다.
 * @summary 인사이트 로그 유사도 검색 (Internal)
 */
export const internalControllerSearchInternalInsights = (
    params: InternalControllerSearchInternalInsightsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerSearchInternalInsights200>(
      {url: `/internal/insights/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInternalControllerSearchInternalInsightsQueryKey = (params?: InternalControllerSearchInternalInsightsParams,) => {
    return [
    `/internal/insights/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInternalControllerSearchInternalInsightsQueryOptions = <TData = Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError = CommonResponse>(params: InternalControllerSearchInternalInsightsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalControllerSearchInternalInsightsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>> = ({ signal }) => internalControllerSearchInternalInsights(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalControllerSearchInternalInsightsQueryResult = NonNullable<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>>
export type InternalControllerSearchInternalInsightsQueryError = CommonResponse


export function useInternalControllerSearchInternalInsights<TData = Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError = CommonResponse>(
 params: InternalControllerSearchInternalInsightsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>,
          TError,
          Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerSearchInternalInsights<TData = Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError = CommonResponse>(
 params: InternalControllerSearchInternalInsightsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>,
          TError,
          Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerSearchInternalInsights<TData = Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError = CommonResponse>(
 params: InternalControllerSearchInternalInsightsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인사이트 로그 유사도 검색 (Internal)
 */

export function useInternalControllerSearchInternalInsights<TData = Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError = CommonResponse>(
 params: InternalControllerSearchInternalInsightsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerSearchInternalInsights>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalControllerSearchInternalInsightsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI 서버가 insightId별 인사이트 로그 내용을 가져갈 때 사용합니다.
 * @summary 인사이트 로그 단건 조회 (Internal)
 */
export const internalControllerGetInternalInsight = (
    insightId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerGetInternalInsight200>(
      {url: `/internal/insights/${insightId}`, method: 'GET', signal
    },
      options);
    }
  



export const getInternalControllerGetInternalInsightQueryKey = (insightId: number,) => {
    return [
    `/internal/insights/${insightId}`
    ] as const;
    }

    
export const getInternalControllerGetInternalInsightQueryOptions = <TData = Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError = CommonResponse>(insightId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalControllerGetInternalInsightQueryKey(insightId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>> = ({ signal }) => internalControllerGetInternalInsight(insightId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(insightId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalControllerGetInternalInsightQueryResult = NonNullable<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>>
export type InternalControllerGetInternalInsightQueryError = CommonResponse


export function useInternalControllerGetInternalInsight<TData = Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError = CommonResponse>(
 insightId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetInternalInsight>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetInternalInsight>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetInternalInsight<TData = Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError = CommonResponse>(
 insightId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetInternalInsight>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetInternalInsight>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetInternalInsight<TData = Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError = CommonResponse>(
 insightId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 인사이트 로그 단건 조회 (Internal)
 */

export function useInternalControllerGetInternalInsight<TData = Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError = CommonResponse>(
 insightId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalControllerGetInternalInsightQueryOptions(insightId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI 서버가 첨삭 생성 시 원문 조회를 위해 사용합니다.
 * @summary 포트폴리오 원문 조회 (Internal)
 */
export const internalControllerGetInternalPortfolio = (
    portfolioId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerGetInternalPortfolio200>(
      {url: `/internal/portfolios/${portfolioId}`, method: 'GET', signal
    },
      options);
    }
  



export const getInternalControllerGetInternalPortfolioQueryKey = (portfolioId: number,) => {
    return [
    `/internal/portfolios/${portfolioId}`
    ] as const;
    }

    
export const getInternalControllerGetInternalPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError = CommonResponse>(portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalControllerGetInternalPortfolioQueryKey(portfolioId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>> = ({ signal }) => internalControllerGetInternalPortfolio(portfolioId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(portfolioId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalControllerGetInternalPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>>
export type InternalControllerGetInternalPortfolioQueryError = CommonResponse


export function useInternalControllerGetInternalPortfolio<TData = Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetInternalPortfolio<TData = Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>,
          TError,
          Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalControllerGetInternalPortfolio<TData = Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포트폴리오 원문 조회 (Internal)
 */

export function useInternalControllerGetInternalPortfolio<TData = Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalControllerGetInternalPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalControllerGetInternalPortfolioQueryOptions(portfolioId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI 서버의 생성 결과를 저장하기 위한 콜백 API
 * @summary 포트폴리오 AI 생성 결과 저장 (Internal)
 */
export const internalControllerUpdateInternalPortfolio = (
    portfolioId: number,
    updatePortfolioResultReqDTO: UpdatePortfolioResultReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalControllerUpdateInternalPortfolio200>(
      {url: `/internal/portfolios/${portfolioId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePortfolioResultReqDTO, signal
    },
      options);
    }
  


export const getInternalControllerUpdateInternalPortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioResultReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioResultReqDTO}, TContext> => {

const mutationKey = ['internalControllerUpdateInternalPortfolio'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>, {portfolioId: number;data: UpdatePortfolioResultReqDTO}> = (props) => {
          const {portfolioId,data} = props ?? {};

          return  internalControllerUpdateInternalPortfolio(portfolioId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalControllerUpdateInternalPortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>>
    export type InternalControllerUpdateInternalPortfolioMutationBody = UpdatePortfolioResultReqDTO
    export type InternalControllerUpdateInternalPortfolioMutationError = CommonResponse

    /**
 * @summary 포트폴리오 AI 생성 결과 저장 (Internal)
 */
export const useInternalControllerUpdateInternalPortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioResultReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalControllerUpdateInternalPortfolio>>,
        TError,
        {portfolioId: number;data: UpdatePortfolioResultReqDTO},
        TContext
      > => {
      return useMutation(getInternalControllerUpdateInternalPortfolioMutationOptions(options), queryClient);
    }
    