/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppSchemasExperienceMapCreateSessionRequest,
  AppSchemasExperienceMapCreateSessionResponse,
  AppSchemasExperienceMapSessionStateResponse,
  BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost,
  GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams,
  HTTPValidationError,
  MessagesResponse,
  RequestStateResponse,
  RetryStreamRequest
} from '../../models';

import { aiCustomInstance } from '../../../../lib/aiAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 메인 서버가 티켓 발급 과정에서 호출합니다. X-API-Key 인증입니다.
 * @summary 세션 생성
 */
export const createSessionApiV1ExperienceMapSessionsPost = (
    appSchemasExperienceMapCreateSessionRequest: AppSchemasExperienceMapCreateSessionRequest,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<AppSchemasExperienceMapCreateSessionResponse>(
      {url: `/api/v1/experience-map/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: appSchemasExperienceMapCreateSessionRequest, signal
    },
      options);
    }
  


export const getCreateSessionApiV1ExperienceMapSessionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>, TError,{data: AppSchemasExperienceMapCreateSessionRequest}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>, TError,{data: AppSchemasExperienceMapCreateSessionRequest}, TContext> => {

const mutationKey = ['createSessionApiV1ExperienceMapSessionsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>, {data: AppSchemasExperienceMapCreateSessionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSessionApiV1ExperienceMapSessionsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionApiV1ExperienceMapSessionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>>
    export type CreateSessionApiV1ExperienceMapSessionsPostMutationBody = AppSchemasExperienceMapCreateSessionRequest
    export type CreateSessionApiV1ExperienceMapSessionsPostMutationError = HTTPValidationError

    /**
 * @summary 세션 생성
 */
export const useCreateSessionApiV1ExperienceMapSessionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>, TError,{data: AppSchemasExperienceMapCreateSessionRequest}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSessionApiV1ExperienceMapSessionsPost>>,
        TError,
        {data: AppSchemasExperienceMapCreateSessionRequest},
        TContext
      > => {
      return useMutation(getCreateSessionApiV1ExperienceMapSessionsPostMutationOptions(options), queryClient);
    }
    /**
 * 화면 새로고침·재접속 시 호출합니다.
 * @summary 세션 상태 조회
 */
export const getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet = (
    sessionId: string,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<AppSchemasExperienceMapSessionStateResponse>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/state`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryKey = (sessionId: string,) => {
    return [
    `/api/v1/experience-map/sessions/${sessionId}/state`
    ] as const;
    }

    
export const getGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryOptions = <TData = Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError = HTTPValidationError>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>> = ({ signal }) => getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet(sessionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>>
export type GetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryError = HTTPValidationError


export function useGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGet<TData = Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError = HTTPValidationError>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGet<TData = Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError = HTTPValidationError>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>,
          TError,
          Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGet<TData = Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError = HTTPValidationError>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 세션 상태 조회
 */

export function useGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGet<TData = Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError = HTTPValidationError>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionStateApiV1ExperienceMapSessionsSessionIdStateGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionStateApiV1ExperienceMapSessionsSessionIdStateGetQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * SSE 단절 뒤 저장된 결과를 복구합니다.
 * @summary 요청 결과 조회
 */
export const getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet = (
    sessionId: string,
    requestId: string,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<RequestStateResponse>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/requests/${requestId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryKey = (sessionId: string,
    requestId: string,) => {
    return [
    `/api/v1/experience-map/sessions/${sessionId}/requests/${requestId}`
    ] as const;
    }

    
export const getGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError = HTTPValidationError>(sessionId: string,
    requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryKey(sessionId,requestId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>> = ({ signal }) => getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet(sessionId,requestId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId && requestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>>
export type GetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryError = HTTPValidationError


export function useGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError = HTTPValidationError>(
 sessionId: string,
    requestId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError = HTTPValidationError>(
 sessionId: string,
    requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError = HTTPValidationError>(
 sessionId: string,
    requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 요청 결과 조회
 */

export function useGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError = HTTPValidationError>(
 sessionId: string,
    requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRequestStateApiV1ExperienceMapSessionsSessionIdRequestsRequestIdGetQueryOptions(sessionId,requestId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 진행 중인 요청에 중지를 요청합니다(프론트 요청, 2026-09-20).
 * @summary 작업 중지
 */
export const cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost = (
    sessionId: string,
    requestId: string,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<void>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/requests/${requestId}/cancel`, method: 'POST', signal
    },
      options);
    }
  


export const getCancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>, TError,{sessionId: string;requestId: string}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>, TError,{sessionId: string;requestId: string}, TContext> => {

const mutationKey = ['cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>, {sessionId: string;requestId: string}> = (props) => {
          const {sessionId,requestId} = props ?? {};

          return  cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost(sessionId,requestId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>>
    
    export type CancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary 작업 중지
 */
export const useCancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>, TError,{sessionId: string;requestId: string}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPost>>,
        TError,
        {sessionId: string;requestId: string},
        TContext
      > => {
      return useMutation(getCancelRequestApiV1ExperienceMapSessionsSessionIdRequestsRequestIdCancelPostMutationOptions(options), queryClient);
    }
    /**
 * 재접속 시 지난 대화 내용을 이어서 보여줄 때 호출합니다.
 * @summary 대화 히스토리 조회
 */
export const getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet = (
    sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<MessagesResponse>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/messages`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryKey = (sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams,) => {
    return [
    `/api/v1/experience-map/sessions/${sessionId}/messages`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError = HTTPValidationError>(sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryKey(sessionId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>> = ({ signal }) => getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet(sessionId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>>
export type GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryError = HTTPValidationError


export function useGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError = HTTPValidationError>(
 sessionId: string,
    params: undefined |  GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError = HTTPValidationError>(
 sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError = HTTPValidationError>(
 sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 대화 히스토리 조회
 */

export function useGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError = HTTPValidationError>(
 sessionId: string,
    params?: GetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiV1ExperienceMapSessionsSessionIdMessagesGet>>, TError, TData>>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesApiV1ExperienceMapSessionsSessionIdMessagesGetQueryOptions(sessionId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * SSE 로 처리 과정과 결과를 보냅니다. multipart/form-data 입니다.
 * @summary 채팅 스트림
 */
export const chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost = (
    sessionId: string,
    bodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`request`, bodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost.request);
if(bodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost.files !== undefined) {
 bodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost.files.forEach(value => formData.append(`files`, value));
 }

      return aiCustomInstance<unknown>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/chat/stream`, method: 'POST',
       data: formData, signal
    },
      options);
    }
  


export const getChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>, TError,{sessionId: string;data: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>, TError,{sessionId: string;data: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost}, TContext> => {

const mutationKey = ['chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>, {sessionId: string;data: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost}> = (props) => {
          const {sessionId,data} = props ?? {};

          return  chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost(sessionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>>
    export type ChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPostMutationBody = BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost
    export type ChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPostMutationError = HTTPValidationError

    /**
 * @summary 채팅 스트림
 */
export const useChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>, TError,{sessionId: string;data: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost>>,
        TError,
        {sessionId: string;data: BodyChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPost},
        TContext
      > => {
      return useMutation(getChatStreamApiV1ExperienceMapSessionsSessionIdChatStreamPostMutationOptions(options), queryClient);
    }
    /**
 * 세션의 마지막 실패 요청을 실패 지점부터 재실행합니다.
 * @summary 재시도 스트림
 */
export const retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost = (
    sessionId: string,
    retryStreamRequest: RetryStreamRequest,
 options?: SecondParameter<typeof aiCustomInstance>,signal?: AbortSignal
) => {
      
      
      return aiCustomInstance<unknown>(
      {url: `/api/v1/experience-map/sessions/${sessionId}/retry/stream`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: retryStreamRequest, signal
    },
      options);
    }
  


export const getRetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>, TError,{sessionId: string;data: RetryStreamRequest}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>, TError,{sessionId: string;data: RetryStreamRequest}, TContext> => {

const mutationKey = ['retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>, {sessionId: string;data: RetryStreamRequest}> = (props) => {
          const {sessionId,data} = props ?? {};

          return  retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost(sessionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPostMutationResult = NonNullable<Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>>
    export type RetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPostMutationBody = RetryStreamRequest
    export type RetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPostMutationError = HTTPValidationError

    /**
 * @summary 재시도 스트림
 */
export const useRetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>, TError,{sessionId: string;data: RetryStreamRequest}, TContext>, request?: SecondParameter<typeof aiCustomInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPost>>,
        TError,
        {sessionId: string;data: RetryStreamRequest},
        TContext
      > => {
      return useMutation(getRetryStreamApiV1ExperienceMapSessionsSessionIdRetryStreamPostMutationOptions(options), queryClient);
    }
    