/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AgreeMarketingReqDTO,
  AgreeTermsReqDTO,
  CommonResponse,
  UpdateUserNameReqDTO,
  UserControllerAgreeTerms200,
  UserControllerGetExpiringTickets200,
  UserControllerGetExpiringTicketsParams,
  UserControllerGetProfile200,
  UserControllerGetTicketBalance200,
  UserControllerUpdateMarketingConsent200,
  UserControllerUpdateProfile200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사용자의 프로필을 조회합니다.
 * @summary 사용자 프로필 조회
 */
export const userControllerGetProfile = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerGetProfile200>(
      {url: `/users/me`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerGetProfileQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }

    
export const getUserControllerGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetProfile>>> = ({ signal }) => userControllerGetProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetProfile>>>
export type UserControllerGetProfileQueryError = CommonResponse


export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 사용자 프로필 조회
 */

export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자의 이름/닉네임을 변경합니다.
 * @summary 사용자 이름/닉네임 변경
 */
export const userControllerUpdateProfile = (
    updateUserNameReqDTO: UpdateUserNameReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerUpdateProfile200>(
      {url: `/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserNameReqDTO, signal
    },
      options);
    }
  


export const getUserControllerUpdateProfileMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{data: UpdateUserNameReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{data: UpdateUserNameReqDTO}, TContext> => {

const mutationKey = ['userControllerUpdateProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateProfile>>, {data: UpdateUserNameReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateProfile(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateProfile>>>
    export type UserControllerUpdateProfileMutationBody = UpdateUserNameReqDTO
    export type UserControllerUpdateProfileMutationError = CommonResponse

    /**
 * @summary 사용자 이름/닉네임 변경
 */
export const useUserControllerUpdateProfile = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{data: UpdateUserNameReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateProfile>>,
        TError,
        {data: UpdateUserNameReqDTO},
        TContext
      > => {
      return useMutation(getUserControllerUpdateProfileMutationOptions(options), queryClient);
    }
    /**
 * 사용자의 계정을 탈퇴 처리하고 연결된 소셜 로그인 계정을 저장된 OAuth 리프레시 토큰 기반으로 연결 해제합니다.
 * @summary 회원 탈퇴
 */
export const userControllerWithdraw = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/users/me`, method: 'DELETE', signal
    },
      options);
    }
  


export const getUserControllerWithdrawMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdraw>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdraw>>, TError,void, TContext> => {

const mutationKey = ['userControllerWithdraw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerWithdraw>>, void> = () => {
          

          return  userControllerWithdraw(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerWithdrawMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerWithdraw>>>
    
    export type UserControllerWithdrawMutationError = CommonResponse

    /**
 * @summary 회원 탈퇴
 */
export const useUserControllerWithdraw = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdraw>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerWithdraw>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUserControllerWithdrawMutationOptions(options), queryClient);
    }
    /**
 * 회원가입 후 서비스 이용약관, 개인정보 처리방침, 마케팅 수신 동의를 처리합니다. 필수 약관(서비스, 개인정보) 동의 시 사용자 상태가 ACTIVE로 전환됩니다.
 * @summary 온보딩 약관 동의
 */
export const userControllerAgreeTerms = (
    agreeTermsReqDTO: AgreeTermsReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerAgreeTerms200>(
      {url: `/users/me/terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: agreeTermsReqDTO, signal
    },
      options);
    }
  


export const getUserControllerAgreeTermsMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerAgreeTerms>>, TError,{data: AgreeTermsReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerAgreeTerms>>, TError,{data: AgreeTermsReqDTO}, TContext> => {

const mutationKey = ['userControllerAgreeTerms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerAgreeTerms>>, {data: AgreeTermsReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  userControllerAgreeTerms(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerAgreeTermsMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerAgreeTerms>>>
    export type UserControllerAgreeTermsMutationBody = AgreeTermsReqDTO
    export type UserControllerAgreeTermsMutationError = CommonResponse

    /**
 * @summary 온보딩 약관 동의
 */
export const useUserControllerAgreeTerms = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerAgreeTerms>>, TError,{data: AgreeTermsReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerAgreeTerms>>,
        TError,
        {data: AgreeTermsReqDTO},
        TContext
      > => {
      return useMutation(getUserControllerAgreeTermsMutationOptions(options), queryClient);
    }
    /**
 * 사용자의 잔여 이용권 수량을 경험 정리, 포트폴리오 첨삭 유형별로 조회합니다.
 * @summary 잔여 이용권 조회
 */
export const userControllerGetTicketBalance = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerGetTicketBalance200>(
      {url: `/users/me/tickets`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerGetTicketBalanceQueryKey = () => {
    return [
    `/users/me/tickets`
    ] as const;
    }

    
export const getUserControllerGetTicketBalanceQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetTicketBalanceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetTicketBalance>>> = ({ signal }) => userControllerGetTicketBalance(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetTicketBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetTicketBalance>>>
export type UserControllerGetTicketBalanceQueryError = CommonResponse


export function useUserControllerGetTicketBalance<TData = Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetTicketBalance>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetTicketBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetTicketBalance<TData = Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetTicketBalance>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetTicketBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetTicketBalance<TData = Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 잔여 이용권 조회
 */

export function useUserControllerGetTicketBalance<TData = Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetTicketBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetTicketBalanceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 지정한 기간(days) 내 만료 예정인 이용권 수량과 가장 빨리 만료되는 일자를 유형별로 조회합니다.
 * @summary 만료 예정 이용권 조회
 */
export const userControllerGetExpiringTickets = (
    params?: UserControllerGetExpiringTicketsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerGetExpiringTickets200>(
      {url: `/users/me/tickets/expiring`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getUserControllerGetExpiringTicketsQueryKey = (params?: UserControllerGetExpiringTicketsParams,) => {
    return [
    `/users/me/tickets/expiring`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getUserControllerGetExpiringTicketsQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError = CommonResponse>(params?: UserControllerGetExpiringTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetExpiringTicketsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>> = ({ signal }) => userControllerGetExpiringTickets(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetExpiringTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>>
export type UserControllerGetExpiringTicketsQueryError = CommonResponse


export function useUserControllerGetExpiringTickets<TData = Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError = CommonResponse>(
 params: undefined |  UserControllerGetExpiringTicketsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetExpiringTickets>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetExpiringTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetExpiringTickets<TData = Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError = CommonResponse>(
 params?: UserControllerGetExpiringTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetExpiringTickets>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetExpiringTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetExpiringTickets<TData = Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError = CommonResponse>(
 params?: UserControllerGetExpiringTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 만료 예정 이용권 조회
 */

export function useUserControllerGetExpiringTickets<TData = Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError = CommonResponse>(
 params?: UserControllerGetExpiringTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetExpiringTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetExpiringTicketsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 사용자의 마케팅 정보 수신 동의 여부를 동의 -> 비동의 또는 비동의 -> 동의로 변경합니다.
 * @summary 마케팅 정보 수신 동의 여부 변경
 */
export const userControllerUpdateMarketingConsent = (
    agreeMarketingReqDTO: AgreeMarketingReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserControllerUpdateMarketingConsent200>(
      {url: `/users/me/marketing-consent`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: agreeMarketingReqDTO, signal
    },
      options);
    }
  


export const getUserControllerUpdateMarketingConsentMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>, TError,{data: AgreeMarketingReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>, TError,{data: AgreeMarketingReqDTO}, TContext> => {

const mutationKey = ['userControllerUpdateMarketingConsent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>, {data: AgreeMarketingReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateMarketingConsent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateMarketingConsentMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>>
    export type UserControllerUpdateMarketingConsentMutationBody = AgreeMarketingReqDTO
    export type UserControllerUpdateMarketingConsentMutationError = CommonResponse

    /**
 * @summary 마케팅 정보 수신 동의 여부 변경
 */
export const useUserControllerUpdateMarketingConsent = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>, TError,{data: AgreeMarketingReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateMarketingConsent>>,
        TError,
        {data: AgreeMarketingReqDTO},
        TContext
      > => {
      return useMutation(getUserControllerUpdateMarketingConsentMutationOptions(options), queryClient);
    }
    