/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  TemplateControllerGetTemplates200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 섹션별 level 4 카테고리 슬롯과 level 5 하위 템플릿(담당업무/문제해결) 목록을 조회합니다. slot_id, placeholder, 작성 예시를 포함합니다.
 * @summary 블록 템플릿 카탈로그 조회
 */
export const templateControllerGetTemplates = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TemplateControllerGetTemplates200>(
      {url: `/templates`, method: 'GET', signal
    },
      options);
    }
  



export const getTemplateControllerGetTemplatesQueryKey = () => {
    return [
    `/templates`
    ] as const;
    }

    
export const getTemplateControllerGetTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateControllerGetTemplatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateControllerGetTemplates>>> = ({ signal }) => templateControllerGetTemplates(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateControllerGetTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof templateControllerGetTemplates>>>
export type TemplateControllerGetTemplatesQueryError = CommonResponse


export function useTemplateControllerGetTemplates<TData = Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateControllerGetTemplates>>,
          TError,
          Awaited<ReturnType<typeof templateControllerGetTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateControllerGetTemplates<TData = Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateControllerGetTemplates>>,
          TError,
          Awaited<ReturnType<typeof templateControllerGetTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateControllerGetTemplates<TData = Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 블록 템플릿 카탈로그 조회
 */

export function useTemplateControllerGetTemplates<TData = Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateControllerGetTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




