/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  EventControllerClaimEventReward200,
  EventControllerGetFeedbackModal200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 내 보상 상태에 따라 피드백 모달 좌/우 버전 표시용 데이터를 반환합니다.
 * @summary 이벤트 피드백 모달 상태 조회
 */
export const eventControllerGetFeedbackModal = (
    eventCode: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EventControllerGetFeedbackModal200>(
      {url: `/events/${eventCode}/feedback-modal`, method: 'GET', signal
    },
      options);
    }
  



export const getEventControllerGetFeedbackModalQueryKey = (eventCode: string,) => {
    return [
    `/events/${eventCode}/feedback-modal`
    ] as const;
    }

    
export const getEventControllerGetFeedbackModalQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError = CommonResponse>(eventCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerGetFeedbackModalQueryKey(eventCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>> = ({ signal }) => eventControllerGetFeedbackModal(eventCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(eventCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventControllerGetFeedbackModalQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>>
export type EventControllerGetFeedbackModalQueryError = CommonResponse


export function useEventControllerGetFeedbackModal<TData = Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError = CommonResponse>(
 eventCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetFeedbackModal<TData = Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError = CommonResponse>(
 eventCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>,
          TError,
          Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventControllerGetFeedbackModal<TData = Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError = CommonResponse>(
 eventCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 이벤트 피드백 모달 상태 조회
 */

export function useEventControllerGetFeedbackModal<TData = Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError = CommonResponse>(
 eventCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventControllerGetFeedbackModal>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventControllerGetFeedbackModalQueryOptions(eventCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 챌린지 완료 사용자가 이벤트 보상을 직접 수령합니다. 이미 수령했거나 조건 미달성인 경우 실패합니다.
 * @summary 이벤트 보상 수령
 */
export const eventControllerClaimEventReward = (
    eventCode: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EventControllerClaimEventReward200>(
      {url: `/events/${eventCode}/reward-claim`, method: 'POST', signal
    },
      options);
    }
  


export const getEventControllerClaimEventRewardMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerClaimEventReward>>, TError,{eventCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerClaimEventReward>>, TError,{eventCode: string}, TContext> => {

const mutationKey = ['eventControllerClaimEventReward'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerClaimEventReward>>, {eventCode: string}> = (props) => {
          const {eventCode} = props ?? {};

          return  eventControllerClaimEventReward(eventCode,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerClaimEventRewardMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerClaimEventReward>>>
    
    export type EventControllerClaimEventRewardMutationError = CommonResponse

    /**
 * @summary 이벤트 보상 수령
 */
export const useEventControllerClaimEventReward = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerClaimEventReward>>, TError,{eventCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerClaimEventReward>>,
        TError,
        {eventCode: string},
        TContext
      > => {
      return useMutation(getEventControllerClaimEventRewardMutationOptions(options), queryClient);
    }
    