/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 세션 생성 요청
 */
export interface AppSchemasInterviewCreateSessionRequest {
  /**
   * 사용자 ID
   * @minLength 1
   */
  user_id: string;
  /**
   * 정리할 경험/프로젝트 이름
   * @minLength 1
   */
  experience_name: string;
}
