/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 첨삭 타입
 */
export type CorrectionLineType = typeof CorrectionLineType[keyof typeof CorrectionLineType];


export const CorrectionLineType = {
  reduce: 'reduce',
  keep: 'keep',
  emphasize: 'emphasize',
} as const;
