/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 커밋 items에서 제외된 항목.

validate 보정을 초과해 AI 서버가 떨어뜨린 것이므로 메인 서버는 존재를 모른다.
 */
export interface DroppedItem {
  item_id: string;
  /** 예: validation_retry_exceeded */
  reason: string;
}
