/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */
import type { PortfolioStatus } from './portfolioStatus';

/**
 * 포트폴리오 생성 응답 (202 Accepted)
 */
export interface GeneratePortfolioResponse {
  /** 생성된 포트폴리오 ID */
  portfolio_id: string;
  /** 현재 생성 상태 */
  status: PortfolioStatus;
}
