/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */
import type { InsightLogSchema } from './insightLogSchema';

/**
 * 턴별 인사이트 복원 기록 스키마
 */
export interface InsightTurnRecordSchema {
  /**
   * 사용자 턴 번호
   * @minimum 1
   */
  turn_number: number;
  /** 해당 턴의 사용자 메시지 */
  user_message: string;
  /** 해당 턴에서 멘션된 인사이트 ID */
  mentioned_insight?: string | null;
  /** 해당 턴에서 조회된 인사이트 카드 목록 */
  insights?: InsightLogSchema[];
}
