/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * PDF 추출 요청 접수 응답
 */
export interface PdfExtractionAcceptedResponse {
  /** 첨삭 ID */
  correction_id: string;
  /** 현재 처리 상태 */
  status: string;
  /** 처리 시작 안내 메시지 */
  message: string;
}
