/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */
import type { CommitResult } from './commitResult';
import type { RequestErrorInfo } from './requestErrorInfo';
import type { RequestStateResponseStatus } from './requestStateResponseStatus';
import type { SuggestionInfo } from './suggestionInfo';

/**
 * SSE 단절 뒤 요청 상태와 저장 결과를 복구한다.
 */
export interface RequestStateResponse {
  request_id: string;
  status: RequestStateResponseStatus;
  result?: CommitResult | null;
  suggestion?: SuggestionInfo | null;
  error?: RequestErrorInfo | null;
}
