/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo AI
 * 포트폴리오 정리를 도와주는 AI 인터뷰 에이전트 API
 * OpenAPI spec version: 0.1.0
 */

export type SuggestionGapGapType = typeof SuggestionGapGapType[keyof typeof SuggestionGapGapType];


export const SuggestionGapGapType = {
  extend_block: 'extend_block',
  new_child_block: 'new_child_block',
} as const;
