/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthControllerGoogleLoginParams,
  AuthControllerKakaoLoginParams,
  AuthControllerNaverLoginParams,
  CommonResponse,
  SendSmsReqDTO,
  VerifySmsReqDTO
} from '../../models';





/**
 * 카카오 인증페이지로 리다이렉트합니다. 스웨거에서 누르지 마세요.
 * @summary 카카오 로그인 트리거
 */
export type authControllerKakaoLoginResponse302 = {
  data: void
  status: 302
}

;
export type authControllerKakaoLoginResponseError = (authControllerKakaoLoginResponse302) & {
  headers: Headers;
};

export type authControllerKakaoLoginResponse = (authControllerKakaoLoginResponseError)

export const getAuthControllerKakaoLoginUrl = (params?: AuthControllerKakaoLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/kakao?${stringifiedParams}` : `/auth/kakao`
}

export const authControllerKakaoLogin = async (params?: AuthControllerKakaoLoginParams, options?: RequestInit): Promise<authControllerKakaoLoginResponse> => {
  
  const res = await fetch(getAuthControllerKakaoLoginUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerKakaoLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerKakaoLoginResponse
}
  




export const getAuthControllerKakaoLoginQueryKey = (params?: AuthControllerKakaoLoginParams,) => {
    return [
    `/auth/kakao`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAuthControllerKakaoLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError = void>(params?: AuthControllerKakaoLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerKakaoLoginQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerKakaoLogin>>> = ({ signal }) => authControllerKakaoLogin(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerKakaoLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerKakaoLogin>>>
export type AuthControllerKakaoLoginQueryError = void


export function useAuthControllerKakaoLogin<TData = Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError = void>(
 params: undefined |  AuthControllerKakaoLoginParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoLogin<TData = Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError = void>(
 params?: AuthControllerKakaoLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoLogin<TData = Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError = void>(
 params?: AuthControllerKakaoLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 카카오 로그인 트리거
 */

export function useAuthControllerKakaoLogin<TData = Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError = void>(
 params?: AuthControllerKakaoLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerKakaoLoginQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 로그인 로직이 이루어지고 프론트로 리다이렉트됩니다. 스웨거에서 누르지 마세요.
 * @summary 카카오 로그인 콜백
 */
export type authControllerKakaoCallbackResponse302 = {
  data: void
  status: 302
}

;
export type authControllerKakaoCallbackResponseError = (authControllerKakaoCallbackResponse302) & {
  headers: Headers;
};

export type authControllerKakaoCallbackResponse = (authControllerKakaoCallbackResponseError)

export const getAuthControllerKakaoCallbackUrl = () => {


  

  return `/auth/kakao/callback`
}

export const authControllerKakaoCallback = async ( options?: RequestInit): Promise<authControllerKakaoCallbackResponse> => {
  
  const res = await fetch(getAuthControllerKakaoCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerKakaoCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerKakaoCallbackResponse
}
  




export const getAuthControllerKakaoCallbackQueryKey = () => {
    return [
    `/auth/kakao/callback`
    ] as const;
    }

    
export const getAuthControllerKakaoCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerKakaoCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerKakaoCallback>>> = ({ signal }) => authControllerKakaoCallback({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerKakaoCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerKakaoCallback>>>
export type AuthControllerKakaoCallbackQueryError = void


export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 카카오 로그인 콜백
 */

export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerKakaoCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 카카오 연결을 끊고, 서비스 내 계정을 비활성화합니다.
 * @summary 서비스 내 카카오 로그인 사용자 탈퇴
 */
export type authControllerKakaoUnlinkResponse200 = {
  data: unknown
  status: 200
}

export type authControllerKakaoUnlinkResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerKakaoUnlinkResponseSuccess = (authControllerKakaoUnlinkResponse200) & {
  headers: Headers;
};
export type authControllerKakaoUnlinkResponseError = (authControllerKakaoUnlinkResponse401) & {
  headers: Headers;
};

export type authControllerKakaoUnlinkResponse = (authControllerKakaoUnlinkResponseSuccess | authControllerKakaoUnlinkResponseError)

export const getAuthControllerKakaoUnlinkUrl = () => {


  

  return `/auth/kakao/unlink`
}

export const authControllerKakaoUnlink = async ( options?: RequestInit): Promise<authControllerKakaoUnlinkResponse> => {
  
  const res = await fetch(getAuthControllerKakaoUnlinkUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerKakaoUnlinkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerKakaoUnlinkResponse
}
  



export const getAuthControllerKakaoUnlinkMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerKakaoUnlink>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerKakaoUnlink>>, TError,void, TContext> => {

const mutationKey = ['authControllerKakaoUnlink'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerKakaoUnlink>>, void> = () => {
          

          return  authControllerKakaoUnlink(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerKakaoUnlinkMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerKakaoUnlink>>>
    
    export type AuthControllerKakaoUnlinkMutationError = CommonResponse

    /**
 * @summary 서비스 내 카카오 로그인 사용자 탈퇴
 */
export const useAuthControllerKakaoUnlink = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerKakaoUnlink>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerKakaoUnlink>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerKakaoUnlinkMutationOptions(options), queryClient);
    }
    /**
 * 구글 인증페이지로 리다이렉트합니다. 스웨거에서 누르지 마세요.
 * @summary 구글 로그인 트리거
 */
export type authControllerGoogleLoginResponse302 = {
  data: void
  status: 302
}

;
export type authControllerGoogleLoginResponseError = (authControllerGoogleLoginResponse302) & {
  headers: Headers;
};

export type authControllerGoogleLoginResponse = (authControllerGoogleLoginResponseError)

export const getAuthControllerGoogleLoginUrl = (params?: AuthControllerGoogleLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/google?${stringifiedParams}` : `/auth/google`
}

export const authControllerGoogleLogin = async (params?: AuthControllerGoogleLoginParams, options?: RequestInit): Promise<authControllerGoogleLoginResponse> => {
  
  const res = await fetch(getAuthControllerGoogleLoginUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerGoogleLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerGoogleLoginResponse
}
  




export const getAuthControllerGoogleLoginQueryKey = (params?: AuthControllerGoogleLoginParams,) => {
    return [
    `/auth/google`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAuthControllerGoogleLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError = void>(params?: AuthControllerGoogleLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGoogleLoginQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleLogin>>> = ({ signal }) => authControllerGoogleLogin(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGoogleLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleLogin>>>
export type AuthControllerGoogleLoginQueryError = void


export function useAuthControllerGoogleLogin<TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError = void>(
 params: undefined |  AuthControllerGoogleLoginParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleLogin<TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError = void>(
 params?: AuthControllerGoogleLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleLogin<TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError = void>(
 params?: AuthControllerGoogleLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 구글 로그인 트리거
 */

export function useAuthControllerGoogleLogin<TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError = void>(
 params?: AuthControllerGoogleLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGoogleLoginQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 로그인 로직이 이루어지고 프론트로 리다이렉트됩니다. 스웨거에서 누르지 마세요.
 * @summary 구글 로그인 콜백
 */
export type authControllerGoogleCallbackResponse302 = {
  data: void
  status: 302
}

;
export type authControllerGoogleCallbackResponseError = (authControllerGoogleCallbackResponse302) & {
  headers: Headers;
};

export type authControllerGoogleCallbackResponse = (authControllerGoogleCallbackResponseError)

export const getAuthControllerGoogleCallbackUrl = () => {


  

  return `/auth/google/callback`
}

export const authControllerGoogleCallback = async ( options?: RequestInit): Promise<authControllerGoogleCallbackResponse> => {
  
  const res = await fetch(getAuthControllerGoogleCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerGoogleCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerGoogleCallbackResponse
}
  




export const getAuthControllerGoogleCallbackQueryKey = () => {
    return [
    `/auth/google/callback`
    ] as const;
    }

    
export const getAuthControllerGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGoogleCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleCallback>>> = ({ signal }) => authControllerGoogleCallback({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleCallback>>>
export type AuthControllerGoogleCallbackQueryError = void


export function useAuthControllerGoogleCallback<TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleCallback<TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleCallback<TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 구글 로그인 콜백
 */

export function useAuthControllerGoogleCallback<TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGoogleCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 구글 연결을 끊고, 서비스 내 계정을 비활성화합니다.
 * @summary 서비스 내 구글 로그인 사용자 탈퇴
 */
export type authControllerGoogleUnlinkResponse200 = {
  data: unknown
  status: 200
}

export type authControllerGoogleUnlinkResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerGoogleUnlinkResponseSuccess = (authControllerGoogleUnlinkResponse200) & {
  headers: Headers;
};
export type authControllerGoogleUnlinkResponseError = (authControllerGoogleUnlinkResponse401) & {
  headers: Headers;
};

export type authControllerGoogleUnlinkResponse = (authControllerGoogleUnlinkResponseSuccess | authControllerGoogleUnlinkResponseError)

export const getAuthControllerGoogleUnlinkUrl = () => {


  

  return `/auth/google/unlink`
}

export const authControllerGoogleUnlink = async ( options?: RequestInit): Promise<authControllerGoogleUnlinkResponse> => {
  
  const res = await fetch(getAuthControllerGoogleUnlinkUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerGoogleUnlinkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerGoogleUnlinkResponse
}
  



export const getAuthControllerGoogleUnlinkMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleUnlink>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleUnlink>>, TError,void, TContext> => {

const mutationKey = ['authControllerGoogleUnlink'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGoogleUnlink>>, void> = () => {
          

          return  authControllerGoogleUnlink(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGoogleUnlinkMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleUnlink>>>
    
    export type AuthControllerGoogleUnlinkMutationError = CommonResponse

    /**
 * @summary 서비스 내 구글 로그인 사용자 탈퇴
 */
export const useAuthControllerGoogleUnlink = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGoogleUnlink>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGoogleUnlink>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerGoogleUnlinkMutationOptions(options), queryClient);
    }
    /**
 * 네이버 인증페이지로 리다이렉트합니다. 스웨거에서 누르지 마세요.
 * @summary 네이버 로그인 트리거
 */
export type authControllerNaverLoginResponse302 = {
  data: void
  status: 302
}

;
export type authControllerNaverLoginResponseError = (authControllerNaverLoginResponse302) & {
  headers: Headers;
};

export type authControllerNaverLoginResponse = (authControllerNaverLoginResponseError)

export const getAuthControllerNaverLoginUrl = (params?: AuthControllerNaverLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/naver?${stringifiedParams}` : `/auth/naver`
}

export const authControllerNaverLogin = async (params?: AuthControllerNaverLoginParams, options?: RequestInit): Promise<authControllerNaverLoginResponse> => {
  
  const res = await fetch(getAuthControllerNaverLoginUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerNaverLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerNaverLoginResponse
}
  




export const getAuthControllerNaverLoginQueryKey = (params?: AuthControllerNaverLoginParams,) => {
    return [
    `/auth/naver`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAuthControllerNaverLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerNaverLogin>>, TError = void>(params?: AuthControllerNaverLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerNaverLoginQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerNaverLogin>>> = ({ signal }) => authControllerNaverLogin(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerNaverLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerNaverLogin>>>
export type AuthControllerNaverLoginQueryError = void


export function useAuthControllerNaverLogin<TData = Awaited<ReturnType<typeof authControllerNaverLogin>>, TError = void>(
 params: undefined |  AuthControllerNaverLoginParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerNaverLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerNaverLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerNaverLogin<TData = Awaited<ReturnType<typeof authControllerNaverLogin>>, TError = void>(
 params?: AuthControllerNaverLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerNaverLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerNaverLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerNaverLogin<TData = Awaited<ReturnType<typeof authControllerNaverLogin>>, TError = void>(
 params?: AuthControllerNaverLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 네이버 로그인 트리거
 */

export function useAuthControllerNaverLogin<TData = Awaited<ReturnType<typeof authControllerNaverLogin>>, TError = void>(
 params?: AuthControllerNaverLoginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerNaverLoginQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 로그인 로직이 이루어지고 프론트로 리다이렉트됩니다. 스웨거에서 누르지 마세요.
 * @summary 네이버 로그인 콜백
 */
export type authControllerNaverCallbackResponse302 = {
  data: void
  status: 302
}

;
export type authControllerNaverCallbackResponseError = (authControllerNaverCallbackResponse302) & {
  headers: Headers;
};

export type authControllerNaverCallbackResponse = (authControllerNaverCallbackResponseError)

export const getAuthControllerNaverCallbackUrl = () => {


  

  return `/auth/naver/callback`
}

export const authControllerNaverCallback = async ( options?: RequestInit): Promise<authControllerNaverCallbackResponse> => {
  
  const res = await fetch(getAuthControllerNaverCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerNaverCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerNaverCallbackResponse
}
  




export const getAuthControllerNaverCallbackQueryKey = () => {
    return [
    `/auth/naver/callback`
    ] as const;
    }

    
export const getAuthControllerNaverCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerNaverCallback>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerNaverCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerNaverCallback>>> = ({ signal }) => authControllerNaverCallback({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerNaverCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerNaverCallback>>>
export type AuthControllerNaverCallbackQueryError = void


export function useAuthControllerNaverCallback<TData = Awaited<ReturnType<typeof authControllerNaverCallback>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerNaverCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerNaverCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerNaverCallback<TData = Awaited<ReturnType<typeof authControllerNaverCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerNaverCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerNaverCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerNaverCallback<TData = Awaited<ReturnType<typeof authControllerNaverCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 네이버 로그인 콜백
 */

export function useAuthControllerNaverCallback<TData = Awaited<ReturnType<typeof authControllerNaverCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerNaverCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerNaverCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 네이버 연결을 끊고, 서비스 내 계정을 비활성화합니다.
 * @summary 서비스 내 네이버 로그인 사용자 탈퇴
 */
export type authControllerNaverUnlinkResponse200 = {
  data: unknown
  status: 200
}

export type authControllerNaverUnlinkResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerNaverUnlinkResponseSuccess = (authControllerNaverUnlinkResponse200) & {
  headers: Headers;
};
export type authControllerNaverUnlinkResponseError = (authControllerNaverUnlinkResponse401) & {
  headers: Headers;
};

export type authControllerNaverUnlinkResponse = (authControllerNaverUnlinkResponseSuccess | authControllerNaverUnlinkResponseError)

export const getAuthControllerNaverUnlinkUrl = () => {


  

  return `/auth/naver/unlink`
}

export const authControllerNaverUnlink = async ( options?: RequestInit): Promise<authControllerNaverUnlinkResponse> => {
  
  const res = await fetch(getAuthControllerNaverUnlinkUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerNaverUnlinkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerNaverUnlinkResponse
}
  



export const getAuthControllerNaverUnlinkMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerNaverUnlink>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerNaverUnlink>>, TError,void, TContext> => {

const mutationKey = ['authControllerNaverUnlink'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerNaverUnlink>>, void> = () => {
          

          return  authControllerNaverUnlink(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerNaverUnlinkMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerNaverUnlink>>>
    
    export type AuthControllerNaverUnlinkMutationError = CommonResponse

    /**
 * @summary 서비스 내 네이버 로그인 사용자 탈퇴
 */
export const useAuthControllerNaverUnlink = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerNaverUnlink>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerNaverUnlink>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerNaverUnlinkMutationOptions(options), queryClient);
    }
    /**
 * 유효한 refreshToken을 사용해 accessToken을 발급 받습니다.
 * @summary 토큰 재발급
 */
export type authControllerHandleRefreshResponse201 = {
  data: unknown
  status: 201
}

export type authControllerHandleRefreshResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerHandleRefreshResponseSuccess = (authControllerHandleRefreshResponse201) & {
  headers: Headers;
};
export type authControllerHandleRefreshResponseError = (authControllerHandleRefreshResponse401) & {
  headers: Headers;
};

export type authControllerHandleRefreshResponse = (authControllerHandleRefreshResponseSuccess | authControllerHandleRefreshResponseError)

export const getAuthControllerHandleRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const authControllerHandleRefresh = async ( options?: RequestInit): Promise<authControllerHandleRefreshResponse> => {
  
  const res = await fetch(getAuthControllerHandleRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerHandleRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerHandleRefreshResponse
}
  



export const getAuthControllerHandleRefreshMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleRefresh>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleRefresh>>, TError,void, TContext> => {

const mutationKey = ['authControllerHandleRefresh'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerHandleRefresh>>, void> = () => {
          

          return  authControllerHandleRefresh(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerHandleRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerHandleRefresh>>>
    
    export type AuthControllerHandleRefreshMutationError = CommonResponse

    /**
 * @summary 토큰 재발급
 */
export const useAuthControllerHandleRefresh = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleRefresh>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerHandleRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerHandleRefreshMutationOptions(options), queryClient);
    }
    /**
 * JWT 토큰을 만료시키고 서버에서 로그아웃을 수행합니다.
 * @summary 로그아웃
 */
export type authControllerHandleLogoutResponse200 = {
  data: unknown
  status: 200
}

export type authControllerHandleLogoutResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerHandleLogoutResponseSuccess = (authControllerHandleLogoutResponse200) & {
  headers: Headers;
};
export type authControllerHandleLogoutResponseError = (authControllerHandleLogoutResponse401) & {
  headers: Headers;
};

export type authControllerHandleLogoutResponse = (authControllerHandleLogoutResponseSuccess | authControllerHandleLogoutResponseError)

export const getAuthControllerHandleLogoutUrl = () => {


  

  return `/auth/logout`
}

export const authControllerHandleLogout = async ( options?: RequestInit): Promise<authControllerHandleLogoutResponse> => {
  
  const res = await fetch(getAuthControllerHandleLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerHandleLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerHandleLogoutResponse
}
  



export const getAuthControllerHandleLogoutMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleLogout>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerHandleLogout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerHandleLogout>>, void> = () => {
          

          return  authControllerHandleLogout(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerHandleLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerHandleLogout>>>
    
    export type AuthControllerHandleLogoutMutationError = CommonResponse

    /**
 * @summary 로그아웃
 */
export const useAuthControllerHandleLogout = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleLogout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerHandleLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerHandleLogoutMutationOptions(options), queryClient);
    }
    /**
 * 전화번호 인증번호를 발송합니다.
 * @summary 전화번호 인증번호 발송
 */
export type authControllerHandleSmsSendResponse200 = {
  data: unknown
  status: 200
}

export type authControllerHandleSmsSendResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerHandleSmsSendResponse409 = {
  data: CommonResponse
  status: 409
}

export type authControllerHandleSmsSendResponseSuccess = (authControllerHandleSmsSendResponse200) & {
  headers: Headers;
};
export type authControllerHandleSmsSendResponseError = (authControllerHandleSmsSendResponse401 | authControllerHandleSmsSendResponse409) & {
  headers: Headers;
};

export type authControllerHandleSmsSendResponse = (authControllerHandleSmsSendResponseSuccess | authControllerHandleSmsSendResponseError)

export const getAuthControllerHandleSmsSendUrl = () => {


  

  return `/auth/sms/send`
}

export const authControllerHandleSmsSend = async (sendSmsReqDTO: SendSmsReqDTO, options?: RequestInit): Promise<authControllerHandleSmsSendResponse> => {
  
  const res = await fetch(getAuthControllerHandleSmsSendUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendSmsReqDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerHandleSmsSendResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerHandleSmsSendResponse
}
  



export const getAuthControllerHandleSmsSendMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsSend>>, TError,{data: SendSmsReqDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsSend>>, TError,{data: SendSmsReqDTO}, TContext> => {

const mutationKey = ['authControllerHandleSmsSend'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerHandleSmsSend>>, {data: SendSmsReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  authControllerHandleSmsSend(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerHandleSmsSendMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerHandleSmsSend>>>
    export type AuthControllerHandleSmsSendMutationBody = SendSmsReqDTO
    export type AuthControllerHandleSmsSendMutationError = CommonResponse

    /**
 * @summary 전화번호 인증번호 발송
 */
export const useAuthControllerHandleSmsSend = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsSend>>, TError,{data: SendSmsReqDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerHandleSmsSend>>,
        TError,
        {data: SendSmsReqDTO},
        TContext
      > => {
      return useMutation(getAuthControllerHandleSmsSendMutationOptions(options), queryClient);
    }
    /**
 * 발송된 인증정보가 올바른지 확인합니다.
 * @summary 전화번호 인증번호 검증
 */
export type authControllerHandleSmsVerifyResponse200 = {
  data: unknown
  status: 200
}

export type authControllerHandleSmsVerifyResponse400 = {
  data: CommonResponse
  status: 400
}

export type authControllerHandleSmsVerifyResponse401 = {
  data: CommonResponse
  status: 401
}

export type authControllerHandleSmsVerifyResponse404 = {
  data: CommonResponse
  status: 404
}

export type authControllerHandleSmsVerifyResponseSuccess = (authControllerHandleSmsVerifyResponse200) & {
  headers: Headers;
};
export type authControllerHandleSmsVerifyResponseError = (authControllerHandleSmsVerifyResponse400 | authControllerHandleSmsVerifyResponse401 | authControllerHandleSmsVerifyResponse404) & {
  headers: Headers;
};

export type authControllerHandleSmsVerifyResponse = (authControllerHandleSmsVerifyResponseSuccess | authControllerHandleSmsVerifyResponseError)

export const getAuthControllerHandleSmsVerifyUrl = () => {


  

  return `/auth/sms/verify`
}

export const authControllerHandleSmsVerify = async (verifySmsReqDTO: VerifySmsReqDTO, options?: RequestInit): Promise<authControllerHandleSmsVerifyResponse> => {
  
  const res = await fetch(getAuthControllerHandleSmsVerifyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifySmsReqDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerHandleSmsVerifyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerHandleSmsVerifyResponse
}
  



export const getAuthControllerHandleSmsVerifyMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsVerify>>, TError,{data: VerifySmsReqDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsVerify>>, TError,{data: VerifySmsReqDTO}, TContext> => {

const mutationKey = ['authControllerHandleSmsVerify'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerHandleSmsVerify>>, {data: VerifySmsReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  authControllerHandleSmsVerify(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerHandleSmsVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerHandleSmsVerify>>>
    export type AuthControllerHandleSmsVerifyMutationBody = VerifySmsReqDTO
    export type AuthControllerHandleSmsVerifyMutationError = CommonResponse

    /**
 * @summary 전화번호 인증번호 검증
 */
export const useAuthControllerHandleSmsVerify = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerHandleSmsVerify>>, TError,{data: VerifySmsReqDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerHandleSmsVerify>>,
        TError,
        {data: VerifySmsReqDTO},
        TContext
      > => {
      return useMutation(getAuthControllerHandleSmsVerifyMutationOptions(options), queryClient);
    }
    