/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  CreateExternalPortfolioReqDTO,
  ExternalPortfolioControllerCreateExternalPortfolioBlock200,
  ExternalPortfolioControllerExtractPortfoliosBody,
  ExternalPortfolioControllerGetExternalPortfolios200,
  ExternalPortfolioControllerGetExternalPortfoliosParams,
  ExternalPortfolioControllerUpdateExternalPortfolio200,
  PortfolioControllerExportPortfolio200,
  PortfolioControllerGetPortfolio200,
  PortfolioControllerUpdatePortfolio200,
  UpdatePortfolioBlockReqDTO,
  UpdatePortfolioReqDTO
} from '../../models';





/**
 * 경험 정리가 완료된 포트폴리오를 조회합니다.
 * @summary 개별 포트폴리오 조회
 */
export type portfolioControllerGetPortfolioResponse200 = {
  data: PortfolioControllerGetPortfolio200
  status: 200
}

export type portfolioControllerGetPortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type portfolioControllerGetPortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type portfolioControllerGetPortfolioResponseSuccess = (portfolioControllerGetPortfolioResponse200) & {
  headers: Headers;
};
export type portfolioControllerGetPortfolioResponseError = (portfolioControllerGetPortfolioResponse401 | portfolioControllerGetPortfolioResponse404) & {
  headers: Headers;
};

export type portfolioControllerGetPortfolioResponse = (portfolioControllerGetPortfolioResponseSuccess | portfolioControllerGetPortfolioResponseError)

export const getPortfolioControllerGetPortfolioUrl = (portfolioId: number,) => {


  

  return `/portfolios/${portfolioId}`
}

export const portfolioControllerGetPortfolio = async (portfolioId: number, options?: RequestInit): Promise<portfolioControllerGetPortfolioResponse> => {
  
  const res = await fetch(getPortfolioControllerGetPortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: portfolioControllerGetPortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as portfolioControllerGetPortfolioResponse
}
  




export const getPortfolioControllerGetPortfolioQueryKey = (portfolioId: number,) => {
    return [
    `/portfolios/${portfolioId}`
    ] as const;
    }

    
export const getPortfolioControllerGetPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError = CommonResponse>(portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioControllerGetPortfolioQueryKey(portfolioId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>> = ({ signal }) => portfolioControllerGetPortfolio(portfolioId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(portfolioId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PortfolioControllerGetPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>>
export type PortfolioControllerGetPortfolioQueryError = CommonResponse


export function usePortfolioControllerGetPortfolio<TData = Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>,
          TError,
          Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioControllerGetPortfolio<TData = Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>,
          TError,
          Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioControllerGetPortfolio<TData = Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 개별 포트폴리오 조회
 */

export function usePortfolioControllerGetPortfolio<TData = Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError = CommonResponse>(
 portfolioId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerGetPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPortfolioControllerGetPortfolioQueryOptions(portfolioId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 경험 정리가 완료된 포트폴리오의 내용을 수정합니다.
 * @summary 개별 포트폴리오 수정
 */
export type portfolioControllerUpdatePortfolioResponse200 = {
  data: PortfolioControllerUpdatePortfolio200
  status: 200
}

export type portfolioControllerUpdatePortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type portfolioControllerUpdatePortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type portfolioControllerUpdatePortfolioResponseSuccess = (portfolioControllerUpdatePortfolioResponse200) & {
  headers: Headers;
};
export type portfolioControllerUpdatePortfolioResponseError = (portfolioControllerUpdatePortfolioResponse401 | portfolioControllerUpdatePortfolioResponse404) & {
  headers: Headers;
};

export type portfolioControllerUpdatePortfolioResponse = (portfolioControllerUpdatePortfolioResponseSuccess | portfolioControllerUpdatePortfolioResponseError)

export const getPortfolioControllerUpdatePortfolioUrl = (portfolioId: number,) => {


  

  return `/portfolios/${portfolioId}`
}

export const portfolioControllerUpdatePortfolio = async (portfolioId: number,
    updatePortfolioReqDTO: UpdatePortfolioReqDTO, options?: RequestInit): Promise<portfolioControllerUpdatePortfolioResponse> => {
  
  const res = await fetch(getPortfolioControllerUpdatePortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePortfolioReqDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: portfolioControllerUpdatePortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as portfolioControllerUpdatePortfolioResponse
}
  



export const getPortfolioControllerUpdatePortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioReqDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioReqDTO}, TContext> => {

const mutationKey = ['portfolioControllerUpdatePortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>, {portfolioId: number;data: UpdatePortfolioReqDTO}> = (props) => {
          const {portfolioId,data} = props ?? {};

          return  portfolioControllerUpdatePortfolio(portfolioId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerUpdatePortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>>
    export type PortfolioControllerUpdatePortfolioMutationBody = UpdatePortfolioReqDTO
    export type PortfolioControllerUpdatePortfolioMutationError = CommonResponse

    /**
 * @summary 개별 포트폴리오 수정
 */
export const usePortfolioControllerUpdatePortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioReqDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerUpdatePortfolio>>,
        TError,
        {portfolioId: number;data: UpdatePortfolioReqDTO},
        TContext
      > => {
      return useMutation(getPortfolioControllerUpdatePortfolioMutationOptions(options), queryClient);
    }
    /**
 * 경험 정리가 완료된 포트폴리오의 내용을 삭제합니다.
 * @summary 개별 포트폴리오 삭제
 */
export type portfolioControllerDeletePortfolioResponse200 = {
  data: unknown
  status: 200
}

export type portfolioControllerDeletePortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type portfolioControllerDeletePortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type portfolioControllerDeletePortfolioResponseSuccess = (portfolioControllerDeletePortfolioResponse200) & {
  headers: Headers;
};
export type portfolioControllerDeletePortfolioResponseError = (portfolioControllerDeletePortfolioResponse401 | portfolioControllerDeletePortfolioResponse404) & {
  headers: Headers;
};

export type portfolioControllerDeletePortfolioResponse = (portfolioControllerDeletePortfolioResponseSuccess | portfolioControllerDeletePortfolioResponseError)

export const getPortfolioControllerDeletePortfolioUrl = (portfolioId: number,) => {


  

  return `/portfolios/${portfolioId}`
}

export const portfolioControllerDeletePortfolio = async (portfolioId: number, options?: RequestInit): Promise<portfolioControllerDeletePortfolioResponse> => {
  
  const res = await fetch(getPortfolioControllerDeletePortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: portfolioControllerDeletePortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as portfolioControllerDeletePortfolioResponse
}
  



export const getPortfolioControllerDeletePortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>, TError,{portfolioId: number}, TContext> => {

const mutationKey = ['portfolioControllerDeletePortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>, {portfolioId: number}> = (props) => {
          const {portfolioId} = props ?? {};

          return  portfolioControllerDeletePortfolio(portfolioId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerDeletePortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>>
    
    export type PortfolioControllerDeletePortfolioMutationError = CommonResponse

    /**
 * @summary 개별 포트폴리오 삭제
 */
export const usePortfolioControllerDeletePortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerDeletePortfolio>>,
        TError,
        {portfolioId: number},
        TContext
      > => {
      return useMutation(getPortfolioControllerDeletePortfolioMutationOptions(options), queryClient);
    }
    /**
 * 경험 정리가 완료된 포트폴리오를 pdf로 내보냅니다.
 * @summary 포트폴리오 내보내기
 */
export type portfolioControllerExportPortfolioResponse200 = {
  data: PortfolioControllerExportPortfolio200
  status: 200
}

export type portfolioControllerExportPortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type portfolioControllerExportPortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type portfolioControllerExportPortfolioResponseSuccess = (portfolioControllerExportPortfolioResponse200) & {
  headers: Headers;
};
export type portfolioControllerExportPortfolioResponseError = (portfolioControllerExportPortfolioResponse401 | portfolioControllerExportPortfolioResponse404) & {
  headers: Headers;
};

export type portfolioControllerExportPortfolioResponse = (portfolioControllerExportPortfolioResponseSuccess | portfolioControllerExportPortfolioResponseError)

export const getPortfolioControllerExportPortfolioUrl = (portfolioId: number,) => {


  

  return `/portfolios/${portfolioId}/export`
}

export const portfolioControllerExportPortfolio = async (portfolioId: number, options?: RequestInit): Promise<portfolioControllerExportPortfolioResponse> => {
  
  const res = await fetch(getPortfolioControllerExportPortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: portfolioControllerExportPortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as portfolioControllerExportPortfolioResponse
}
  



export const getPortfolioControllerExportPortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>, TError,{portfolioId: number}, TContext> => {

const mutationKey = ['portfolioControllerExportPortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>, {portfolioId: number}> = (props) => {
          const {portfolioId} = props ?? {};

          return  portfolioControllerExportPortfolio(portfolioId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerExportPortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>>
    
    export type PortfolioControllerExportPortfolioMutationError = CommonResponse

    /**
 * @summary 포트폴리오 내보내기
 */
export const usePortfolioControllerExportPortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerExportPortfolio>>,
        TError,
        {portfolioId: number},
        TContext
      > => {
      return useMutation(getPortfolioControllerExportPortfolioMutationOptions(options), queryClient);
    }
    /**
 * 업로드한 포트폴리오 파일에서 텍스트를 추출합니다.
 * @summary PDF 포트폴리오 텍스트 추출
 */
export type externalPortfolioControllerExtractPortfoliosResponse200 = {
  data: unknown
  status: 200
}

export type externalPortfolioControllerExtractPortfoliosResponse401 = {
  data: CommonResponse
  status: 401
}

export type externalPortfolioControllerExtractPortfoliosResponseSuccess = (externalPortfolioControllerExtractPortfoliosResponse200) & {
  headers: Headers;
};
export type externalPortfolioControllerExtractPortfoliosResponseError = (externalPortfolioControllerExtractPortfoliosResponse401) & {
  headers: Headers;
};

export type externalPortfolioControllerExtractPortfoliosResponse = (externalPortfolioControllerExtractPortfoliosResponseSuccess | externalPortfolioControllerExtractPortfoliosResponseError)

export const getExternalPortfolioControllerExtractPortfoliosUrl = () => {


  

  return `/external-portfolios/extract`
}

export const externalPortfolioControllerExtractPortfolios = async (externalPortfolioControllerExtractPortfoliosBody: ExternalPortfolioControllerExtractPortfoliosBody, options?: RequestInit): Promise<externalPortfolioControllerExtractPortfoliosResponse> => {
    const formData = new FormData();
if(externalPortfolioControllerExtractPortfoliosBody.file !== undefined) {
 formData.append(`file`, externalPortfolioControllerExtractPortfoliosBody.file);
 }

  const res = await fetch(getExternalPortfolioControllerExtractPortfoliosUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: externalPortfolioControllerExtractPortfoliosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as externalPortfolioControllerExtractPortfoliosResponse
}
  



export const getExternalPortfolioControllerExtractPortfoliosMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>, TError,{data: ExternalPortfolioControllerExtractPortfoliosBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>, TError,{data: ExternalPortfolioControllerExtractPortfoliosBody}, TContext> => {

const mutationKey = ['externalPortfolioControllerExtractPortfolios'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>, {data: ExternalPortfolioControllerExtractPortfoliosBody}> = (props) => {
          const {data} = props ?? {};

          return  externalPortfolioControllerExtractPortfolios(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExternalPortfolioControllerExtractPortfoliosMutationResult = NonNullable<Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>>
    export type ExternalPortfolioControllerExtractPortfoliosMutationBody = ExternalPortfolioControllerExtractPortfoliosBody
    export type ExternalPortfolioControllerExtractPortfoliosMutationError = CommonResponse

    /**
 * @summary PDF 포트폴리오 텍스트 추출
 */
export const useExternalPortfolioControllerExtractPortfolios = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>, TError,{data: ExternalPortfolioControllerExtractPortfoliosBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof externalPortfolioControllerExtractPortfolios>>,
        TError,
        {data: ExternalPortfolioControllerExtractPortfoliosBody},
        TContext
      > => {
      return useMutation(getExternalPortfolioControllerExtractPortfoliosMutationOptions(options), queryClient);
    }
    /**
 * 텍스트 정리 블록의 활동 블록을 추가합니다. 활동 블록은 최대 5개까지 존재 가능합니다.
 * @summary PDF 포트폴리오 활동 블록 추가
 */
export type externalPortfolioControllerCreateExternalPortfolioBlockResponse200 = {
  data: ExternalPortfolioControllerCreateExternalPortfolioBlock200
  status: 200
}

export type externalPortfolioControllerCreateExternalPortfolioBlockResponse401 = {
  data: CommonResponse
  status: 401
}

export type externalPortfolioControllerCreateExternalPortfolioBlockResponse404 = {
  data: CommonResponse
  status: 404
}

export type externalPortfolioControllerCreateExternalPortfolioBlockResponse409 = {
  data: CommonResponse
  status: 409
}

export type externalPortfolioControllerCreateExternalPortfolioBlockResponseSuccess = (externalPortfolioControllerCreateExternalPortfolioBlockResponse200) & {
  headers: Headers;
};
export type externalPortfolioControllerCreateExternalPortfolioBlockResponseError = (externalPortfolioControllerCreateExternalPortfolioBlockResponse401 | externalPortfolioControllerCreateExternalPortfolioBlockResponse404 | externalPortfolioControllerCreateExternalPortfolioBlockResponse409) & {
  headers: Headers;
};

export type externalPortfolioControllerCreateExternalPortfolioBlockResponse = (externalPortfolioControllerCreateExternalPortfolioBlockResponseSuccess | externalPortfolioControllerCreateExternalPortfolioBlockResponseError)

export const getExternalPortfolioControllerCreateExternalPortfolioBlockUrl = () => {


  

  return `/external-portfolios`
}

export const externalPortfolioControllerCreateExternalPortfolioBlock = async (createExternalPortfolioReqDTO: CreateExternalPortfolioReqDTO, options?: RequestInit): Promise<externalPortfolioControllerCreateExternalPortfolioBlockResponse> => {
  
  const res = await fetch(getExternalPortfolioControllerCreateExternalPortfolioBlockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExternalPortfolioReqDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: externalPortfolioControllerCreateExternalPortfolioBlockResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as externalPortfolioControllerCreateExternalPortfolioBlockResponse
}
  



export const getExternalPortfolioControllerCreateExternalPortfolioBlockMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>, TError,{data: CreateExternalPortfolioReqDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>, TError,{data: CreateExternalPortfolioReqDTO}, TContext> => {

const mutationKey = ['externalPortfolioControllerCreateExternalPortfolioBlock'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>, {data: CreateExternalPortfolioReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  externalPortfolioControllerCreateExternalPortfolioBlock(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExternalPortfolioControllerCreateExternalPortfolioBlockMutationResult = NonNullable<Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>>
    export type ExternalPortfolioControllerCreateExternalPortfolioBlockMutationBody = CreateExternalPortfolioReqDTO
    export type ExternalPortfolioControllerCreateExternalPortfolioBlockMutationError = CommonResponse

    /**
 * @summary PDF 포트폴리오 활동 블록 추가
 */
export const useExternalPortfolioControllerCreateExternalPortfolioBlock = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>, TError,{data: CreateExternalPortfolioReqDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof externalPortfolioControllerCreateExternalPortfolioBlock>>,
        TError,
        {data: CreateExternalPortfolioReqDTO},
        TContext
      > => {
      return useMutation(getExternalPortfolioControllerCreateExternalPortfolioBlockMutationOptions(options), queryClient);
    }
    /**
 * AI가 구조화한 포트폴리오 정보를 조회합니다.
 * @summary PDF 포트폴리오 텍스트 정리 결과 조회
 */
export type externalPortfolioControllerGetExternalPortfoliosResponse200 = {
  data: ExternalPortfolioControllerGetExternalPortfolios200
  status: 200
}

export type externalPortfolioControllerGetExternalPortfoliosResponse401 = {
  data: CommonResponse
  status: 401
}

export type externalPortfolioControllerGetExternalPortfoliosResponse404 = {
  data: CommonResponse
  status: 404
}

export type externalPortfolioControllerGetExternalPortfoliosResponseSuccess = (externalPortfolioControllerGetExternalPortfoliosResponse200) & {
  headers: Headers;
};
export type externalPortfolioControllerGetExternalPortfoliosResponseError = (externalPortfolioControllerGetExternalPortfoliosResponse401 | externalPortfolioControllerGetExternalPortfoliosResponse404) & {
  headers: Headers;
};

export type externalPortfolioControllerGetExternalPortfoliosResponse = (externalPortfolioControllerGetExternalPortfoliosResponseSuccess | externalPortfolioControllerGetExternalPortfoliosResponseError)

export const getExternalPortfolioControllerGetExternalPortfoliosUrl = (params: ExternalPortfolioControllerGetExternalPortfoliosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/external-portfolios?${stringifiedParams}` : `/external-portfolios`
}

export const externalPortfolioControllerGetExternalPortfolios = async (params: ExternalPortfolioControllerGetExternalPortfoliosParams, options?: RequestInit): Promise<externalPortfolioControllerGetExternalPortfoliosResponse> => {
  
  const res = await fetch(getExternalPortfolioControllerGetExternalPortfoliosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: externalPortfolioControllerGetExternalPortfoliosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as externalPortfolioControllerGetExternalPortfoliosResponse
}
  




export const getExternalPortfolioControllerGetExternalPortfoliosQueryKey = (params?: ExternalPortfolioControllerGetExternalPortfoliosParams,) => {
    return [
    `/external-portfolios`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getExternalPortfolioControllerGetExternalPortfoliosQueryOptions = <TData = Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError = CommonResponse>(params: ExternalPortfolioControllerGetExternalPortfoliosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExternalPortfolioControllerGetExternalPortfoliosQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>> = ({ signal }) => externalPortfolioControllerGetExternalPortfolios(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExternalPortfolioControllerGetExternalPortfoliosQueryResult = NonNullable<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>>
export type ExternalPortfolioControllerGetExternalPortfoliosQueryError = CommonResponse


export function useExternalPortfolioControllerGetExternalPortfolios<TData = Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError = CommonResponse>(
 params: ExternalPortfolioControllerGetExternalPortfoliosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>,
          TError,
          Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExternalPortfolioControllerGetExternalPortfolios<TData = Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError = CommonResponse>(
 params: ExternalPortfolioControllerGetExternalPortfoliosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>,
          TError,
          Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExternalPortfolioControllerGetExternalPortfolios<TData = Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError = CommonResponse>(
 params: ExternalPortfolioControllerGetExternalPortfoliosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary PDF 포트폴리오 텍스트 정리 결과 조회
 */

export function useExternalPortfolioControllerGetExternalPortfolios<TData = Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError = CommonResponse>(
 params: ExternalPortfolioControllerGetExternalPortfoliosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof externalPortfolioControllerGetExternalPortfolios>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExternalPortfolioControllerGetExternalPortfoliosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI가 구조화한 포트폴리오 정보를 수정합니다.
 * @summary PDF 포트폴리오 텍스트 정리 결과 수정
 */
export type externalPortfolioControllerUpdateExternalPortfolioResponse200 = {
  data: ExternalPortfolioControllerUpdateExternalPortfolio200
  status: 200
}

export type externalPortfolioControllerUpdateExternalPortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type externalPortfolioControllerUpdateExternalPortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type externalPortfolioControllerUpdateExternalPortfolioResponseSuccess = (externalPortfolioControllerUpdateExternalPortfolioResponse200) & {
  headers: Headers;
};
export type externalPortfolioControllerUpdateExternalPortfolioResponseError = (externalPortfolioControllerUpdateExternalPortfolioResponse401 | externalPortfolioControllerUpdateExternalPortfolioResponse404) & {
  headers: Headers;
};

export type externalPortfolioControllerUpdateExternalPortfolioResponse = (externalPortfolioControllerUpdateExternalPortfolioResponseSuccess | externalPortfolioControllerUpdateExternalPortfolioResponseError)

export const getExternalPortfolioControllerUpdateExternalPortfolioUrl = (portfolioId: number,) => {


  

  return `/external-portfolios/${portfolioId}`
}

export const externalPortfolioControllerUpdateExternalPortfolio = async (portfolioId: number,
    updatePortfolioBlockReqDTO: UpdatePortfolioBlockReqDTO, options?: RequestInit): Promise<externalPortfolioControllerUpdateExternalPortfolioResponse> => {
  
  const res = await fetch(getExternalPortfolioControllerUpdateExternalPortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePortfolioBlockReqDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: externalPortfolioControllerUpdateExternalPortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as externalPortfolioControllerUpdateExternalPortfolioResponse
}
  



export const getExternalPortfolioControllerUpdateExternalPortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioBlockReqDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioBlockReqDTO}, TContext> => {

const mutationKey = ['externalPortfolioControllerUpdateExternalPortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>, {portfolioId: number;data: UpdatePortfolioBlockReqDTO}> = (props) => {
          const {portfolioId,data} = props ?? {};

          return  externalPortfolioControllerUpdateExternalPortfolio(portfolioId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExternalPortfolioControllerUpdateExternalPortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>>
    export type ExternalPortfolioControllerUpdateExternalPortfolioMutationBody = UpdatePortfolioBlockReqDTO
    export type ExternalPortfolioControllerUpdateExternalPortfolioMutationError = CommonResponse

    /**
 * @summary PDF 포트폴리오 텍스트 정리 결과 수정
 */
export const useExternalPortfolioControllerUpdateExternalPortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>, TError,{portfolioId: number;data: UpdatePortfolioBlockReqDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof externalPortfolioControllerUpdateExternalPortfolio>>,
        TError,
        {portfolioId: number;data: UpdatePortfolioBlockReqDTO},
        TContext
      > => {
      return useMutation(getExternalPortfolioControllerUpdateExternalPortfolioMutationOptions(options), queryClient);
    }
    /**
 * AI가 구조화한 포트폴리오 활동을 삭제합니다. (활동 옆 마이너스 버튼을 눌러 활성화)
 * @summary PDF 포트폴리오 텍스트 정리 결과 삭제
 */
export type externalPortfolioControllerDeleteExternalPortfolioResponse200 = {
  data: unknown
  status: 200
}

export type externalPortfolioControllerDeleteExternalPortfolioResponse401 = {
  data: CommonResponse
  status: 401
}

export type externalPortfolioControllerDeleteExternalPortfolioResponse404 = {
  data: CommonResponse
  status: 404
}

export type externalPortfolioControllerDeleteExternalPortfolioResponseSuccess = (externalPortfolioControllerDeleteExternalPortfolioResponse200) & {
  headers: Headers;
};
export type externalPortfolioControllerDeleteExternalPortfolioResponseError = (externalPortfolioControllerDeleteExternalPortfolioResponse401 | externalPortfolioControllerDeleteExternalPortfolioResponse404) & {
  headers: Headers;
};

export type externalPortfolioControllerDeleteExternalPortfolioResponse = (externalPortfolioControllerDeleteExternalPortfolioResponseSuccess | externalPortfolioControllerDeleteExternalPortfolioResponseError)

export const getExternalPortfolioControllerDeleteExternalPortfolioUrl = (portfolioId: number,) => {


  

  return `/external-portfolios/${portfolioId}`
}

export const externalPortfolioControllerDeleteExternalPortfolio = async (portfolioId: number, options?: RequestInit): Promise<externalPortfolioControllerDeleteExternalPortfolioResponse> => {
  
  const res = await fetch(getExternalPortfolioControllerDeleteExternalPortfolioUrl(portfolioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: externalPortfolioControllerDeleteExternalPortfolioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as externalPortfolioControllerDeleteExternalPortfolioResponse
}
  



export const getExternalPortfolioControllerDeleteExternalPortfolioMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>, TError,{portfolioId: number}, TContext> => {

const mutationKey = ['externalPortfolioControllerDeleteExternalPortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>, {portfolioId: number}> = (props) => {
          const {portfolioId} = props ?? {};

          return  externalPortfolioControllerDeleteExternalPortfolio(portfolioId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExternalPortfolioControllerDeleteExternalPortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>>
    
    export type ExternalPortfolioControllerDeleteExternalPortfolioMutationError = CommonResponse

    /**
 * @summary PDF 포트폴리오 텍스트 정리 결과 삭제
 */
export const useExternalPortfolioControllerDeleteExternalPortfolio = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>, TError,{portfolioId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof externalPortfolioControllerDeleteExternalPortfolio>>,
        TError,
        {portfolioId: number},
        TContext
      > => {
      return useMutation(getExternalPortfolioControllerDeleteExternalPortfolioMutationOptions(options), queryClient);
    }
    