/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssessmentControllerClaim200,
  AssessmentControllerCreate200,
  AssessmentControllerGetNextValueBalanceQuestion200,
  AssessmentControllerGetResult200,
  AssessmentControllerGetStatus200,
  CommonResponse,
  CreateAssessmentReqDTO,
  ValueBalanceAnswerReqDTO
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * token을 생략하면 새 세션을 시작해 첫 질문을 반환합니다. token과 함께 sequence·chosen을 보내면 그 답을 기록하고 다음 질문을 반환합니다. 이미 답한 sequence를 다시 보내면(이전 질문으로 돌아가 다시 고르기) 그 지점 이후 기록은 폐기되고 이어서 다시 진행됩니다. 5개 가치의 순위가 모두 확정되면 completed=true와 함께 순위·가중치를 반환하며, 이후에는 응답을 수정할 수 없습니다. 이 순위를 그대로 POST /assessments의 valueRanking에 담아 보내면 됩니다.
 * @summary 가치관 밸런스게임 다음 질문 조회
 */
export const assessmentControllerGetNextValueBalanceQuestion = (
    valueBalanceAnswerReqDTO: ValueBalanceAnswerReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AssessmentControllerGetNextValueBalanceQuestion200>(
      {url: `/assessments/values-balance/next-question`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: valueBalanceAnswerReqDTO, signal
    },
      options);
    }
  


export const getAssessmentControllerGetNextValueBalanceQuestionMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>, TError,{data: ValueBalanceAnswerReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>, TError,{data: ValueBalanceAnswerReqDTO}, TContext> => {

const mutationKey = ['assessmentControllerGetNextValueBalanceQuestion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>, {data: ValueBalanceAnswerReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  assessmentControllerGetNextValueBalanceQuestion(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AssessmentControllerGetNextValueBalanceQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>>
    export type AssessmentControllerGetNextValueBalanceQuestionMutationBody = ValueBalanceAnswerReqDTO
    export type AssessmentControllerGetNextValueBalanceQuestionMutationError = CommonResponse

    /**
 * @summary 가치관 밸런스게임 다음 질문 조회
 */
export const useAssessmentControllerGetNextValueBalanceQuestion = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>, TError,{data: ValueBalanceAnswerReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assessmentControllerGetNextValueBalanceQuestion>>,
        TError,
        {data: ValueBalanceAnswerReqDTO},
        TContext
      > => {
      return useMutation(getAssessmentControllerGetNextValueBalanceQuestionMutationOptions(options), queryClient);
    }
    /**
 * 성향 문항 15개 응답과 확정된 가치관 순위(5개)로 분석을 실행하고 결과를 바로 반환합니다. 로그인 상태로 요청하면 결과가 즉시 내 계정에 연결되고, 비로그인 상태면 이후 claim API로 등록할 수 있습니다.
 * @summary 직무·기업형태 추천 분석 생성
 */
export const assessmentControllerCreate = (
    createAssessmentReqDTO: CreateAssessmentReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AssessmentControllerCreate200>(
      {url: `/assessments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAssessmentReqDTO, signal
    },
      options);
    }
  


export const getAssessmentControllerCreateMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerCreate>>, TError,{data: CreateAssessmentReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerCreate>>, TError,{data: CreateAssessmentReqDTO}, TContext> => {

const mutationKey = ['assessmentControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assessmentControllerCreate>>, {data: CreateAssessmentReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  assessmentControllerCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AssessmentControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof assessmentControllerCreate>>>
    export type AssessmentControllerCreateMutationBody = CreateAssessmentReqDTO
    export type AssessmentControllerCreateMutationError = CommonResponse

    /**
 * @summary 직무·기업형태 추천 분석 생성
 */
export const useAssessmentControllerCreate = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerCreate>>, TError,{data: CreateAssessmentReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assessmentControllerCreate>>,
        TError,
        {data: CreateAssessmentReqDTO},
        TContext
      > => {
      return useMutation(getAssessmentControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * 로그인한 사용자 계정 기준으로 완료된 분석 결과가 있는지 확인합니다. 생성 시점에 로그인 상태였거나, 이후 claim으로 등록한 결과 모두 대상입니다.
 * @summary 직무·기업형태 추천 분석 실행 여부 조회
 */
export const assessmentControllerGetStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AssessmentControllerGetStatus200>(
      {url: `/assessments/status`, method: 'GET', signal
    },
      options);
    }
  



export const getAssessmentControllerGetStatusQueryKey = () => {
    return [
    `/assessments/status`
    ] as const;
    }

    
export const getAssessmentControllerGetStatusQueryOptions = <TData = Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssessmentControllerGetStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof assessmentControllerGetStatus>>> = ({ signal }) => assessmentControllerGetStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssessmentControllerGetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof assessmentControllerGetStatus>>>
export type AssessmentControllerGetStatusQueryError = CommonResponse


export function useAssessmentControllerGetStatus<TData = Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assessmentControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof assessmentControllerGetStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssessmentControllerGetStatus<TData = Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assessmentControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof assessmentControllerGetStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssessmentControllerGetStatus<TData = Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 직무·기업형태 추천 분석 실행 여부 조회
 */

export function useAssessmentControllerGetStatus<TData = Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssessmentControllerGetStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * uuid만 있으면 로그인 여부와 무관하게 누구나 전체 내용을 조회할 수 있어 공유 링크로 사용됩니다.
 * @summary 직무·기업형태 추천 분석 결과 조회
 */
export const assessmentControllerGetResult = (
    uuid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AssessmentControllerGetResult200>(
      {url: `/assessments/${uuid}`, method: 'GET', signal
    },
      options);
    }
  



export const getAssessmentControllerGetResultQueryKey = (uuid: string,) => {
    return [
    `/assessments/${uuid}`
    ] as const;
    }

    
export const getAssessmentControllerGetResultQueryOptions = <TData = Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError = CommonResponse>(uuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssessmentControllerGetResultQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof assessmentControllerGetResult>>> = ({ signal }) => assessmentControllerGetResult(uuid, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssessmentControllerGetResultQueryResult = NonNullable<Awaited<ReturnType<typeof assessmentControllerGetResult>>>
export type AssessmentControllerGetResultQueryError = CommonResponse


export function useAssessmentControllerGetResult<TData = Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError = CommonResponse>(
 uuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assessmentControllerGetResult>>,
          TError,
          Awaited<ReturnType<typeof assessmentControllerGetResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssessmentControllerGetResult<TData = Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError = CommonResponse>(
 uuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assessmentControllerGetResult>>,
          TError,
          Awaited<ReturnType<typeof assessmentControllerGetResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssessmentControllerGetResult<TData = Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError = CommonResponse>(
 uuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 직무·기업형태 추천 분석 결과 조회
 */

export function useAssessmentControllerGetResult<TData = Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError = CommonResponse>(
 uuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assessmentControllerGetResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssessmentControllerGetResultQueryOptions(uuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 익명으로 생성한 분석 결과를 로그인한 내 계정에 연결합니다. 이미 다른 곳에 등록된 결과는 다시 등록할 수 없습니다.
 * @summary 직무·기업형태 추천 분석 결과 소유권 등록
 */
export const assessmentControllerClaim = (
    uuid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AssessmentControllerClaim200>(
      {url: `/assessments/${uuid}/claim`, method: 'POST', signal
    },
      options);
    }
  


export const getAssessmentControllerClaimMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerClaim>>, TError,{uuid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerClaim>>, TError,{uuid: string}, TContext> => {

const mutationKey = ['assessmentControllerClaim'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assessmentControllerClaim>>, {uuid: string}> = (props) => {
          const {uuid} = props ?? {};

          return  assessmentControllerClaim(uuid,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AssessmentControllerClaimMutationResult = NonNullable<Awaited<ReturnType<typeof assessmentControllerClaim>>>
    
    export type AssessmentControllerClaimMutationError = CommonResponse

    /**
 * @summary 직무·기업형태 추천 분석 결과 소유권 등록
 */
export const useAssessmentControllerClaim = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assessmentControllerClaim>>, TError,{uuid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assessmentControllerClaim>>,
        TError,
        {uuid: string},
        TContext
      > => {
      return useMutation(getAssessmentControllerClaimMutationOptions(options), queryClient);
    }
    