/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  CreateExperienceReqDTO,
  ExperienceControllerCreateExperience200,
  ExperienceControllerGetExperience200,
  ExperienceControllerGetExperiences200,
  ExperienceControllerGetExperiencesParams,
  ExperienceControllerUpdateExperience200,
  UpdateExperienceReqDTO
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 새로운 경험 정리를 생성하고, AI와의 대화를 시작합니다. 경험 정리 티켓 1장을 사용합니다. 인당 최대 15개의 경험을 저장할 수 있습니다.
 * @summary 새로운 경험 정리 시작하기
 */
export type experienceControllerCreateExperienceResponse200 = {
  data: ExperienceControllerCreateExperience200
  status: 200
}

export type experienceControllerCreateExperienceResponse401 = {
  data: CommonResponse
  status: 401
}

export type experienceControllerCreateExperienceResponse402 = {
  data: CommonResponse
  status: 402
}

export type experienceControllerCreateExperienceResponse409 = {
  data: CommonResponse
  status: 409
}

export type experienceControllerCreateExperienceResponseSuccess = (experienceControllerCreateExperienceResponse200) & {
  headers: Headers;
};
export type experienceControllerCreateExperienceResponseError = (experienceControllerCreateExperienceResponse401 | experienceControllerCreateExperienceResponse402 | experienceControllerCreateExperienceResponse409) & {
  headers: Headers;
};

export type experienceControllerCreateExperienceResponse = (experienceControllerCreateExperienceResponseSuccess | experienceControllerCreateExperienceResponseError)

export const getExperienceControllerCreateExperienceUrl = () => {


  

  return `/experiences`
}

export const experienceControllerCreateExperience = async (createExperienceReqDTO: CreateExperienceReqDTO, options?: RequestInit): Promise<experienceControllerCreateExperienceResponse> => {
  
  return customInstance<experienceControllerCreateExperienceResponse>(getExperienceControllerCreateExperienceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExperienceReqDTO,)
  }
);}
  



export const getExperienceControllerCreateExperienceMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceControllerCreateExperience>>, TError,{data: CreateExperienceReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof experienceControllerCreateExperience>>, TError,{data: CreateExperienceReqDTO}, TContext> => {

const mutationKey = ['experienceControllerCreateExperience'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof experienceControllerCreateExperience>>, {data: CreateExperienceReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  experienceControllerCreateExperience(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExperienceControllerCreateExperienceMutationResult = NonNullable<Awaited<ReturnType<typeof experienceControllerCreateExperience>>>
    export type ExperienceControllerCreateExperienceMutationBody = CreateExperienceReqDTO
    export type ExperienceControllerCreateExperienceMutationError = CommonResponse

    /**
 * @summary 새로운 경험 정리 시작하기
 */
export const useExperienceControllerCreateExperience = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceControllerCreateExperience>>, TError,{data: CreateExperienceReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof experienceControllerCreateExperience>>,
        TError,
        {data: CreateExperienceReqDTO},
        TContext
      > => {
      return useMutation(getExperienceControllerCreateExperienceMutationOptions(options), queryClient);
    }
    /**
 * 사용자가 생성한 경험 정리 목록을 조회합니다. 검색어를 입력하면 제목에 키워드를 포함하는 목록만 조회됩니다.
 * @summary 경험 정리 목록 조회
 */
export type experienceControllerGetExperiencesResponse200 = {
  data: ExperienceControllerGetExperiences200
  status: 200
}

export type experienceControllerGetExperiencesResponse401 = {
  data: CommonResponse
  status: 401
}

export type experienceControllerGetExperiencesResponseSuccess = (experienceControllerGetExperiencesResponse200) & {
  headers: Headers;
};
export type experienceControllerGetExperiencesResponseError = (experienceControllerGetExperiencesResponse401) & {
  headers: Headers;
};

export type experienceControllerGetExperiencesResponse = (experienceControllerGetExperiencesResponseSuccess | experienceControllerGetExperiencesResponseError)

export const getExperienceControllerGetExperiencesUrl = (params?: ExperienceControllerGetExperiencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/experiences?${stringifiedParams}` : `/experiences`
}

export const experienceControllerGetExperiences = async (params?: ExperienceControllerGetExperiencesParams, options?: RequestInit): Promise<experienceControllerGetExperiencesResponse> => {
  
  return customInstance<experienceControllerGetExperiencesResponse>(getExperienceControllerGetExperiencesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getExperienceControllerGetExperiencesQueryKey = (params?: ExperienceControllerGetExperiencesParams,) => {
    return [
    `/experiences`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getExperienceControllerGetExperiencesQueryOptions = <TData = Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError = CommonResponse>(params?: ExperienceControllerGetExperiencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExperienceControllerGetExperiencesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof experienceControllerGetExperiences>>> = ({ signal }) => experienceControllerGetExperiences(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExperienceControllerGetExperiencesQueryResult = NonNullable<Awaited<ReturnType<typeof experienceControllerGetExperiences>>>
export type ExperienceControllerGetExperiencesQueryError = CommonResponse


export function useExperienceControllerGetExperiences<TData = Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError = CommonResponse>(
 params: undefined |  ExperienceControllerGetExperiencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceControllerGetExperiences>>,
          TError,
          Awaited<ReturnType<typeof experienceControllerGetExperiences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceControllerGetExperiences<TData = Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError = CommonResponse>(
 params?: ExperienceControllerGetExperiencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceControllerGetExperiences>>,
          TError,
          Awaited<ReturnType<typeof experienceControllerGetExperiences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceControllerGetExperiences<TData = Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError = CommonResponse>(
 params?: ExperienceControllerGetExperiencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 경험 정리 목록 조회
 */

export function useExperienceControllerGetExperiences<TData = Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError = CommonResponse>(
 params?: ExperienceControllerGetExperiencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperiences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExperienceControllerGetExperiencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 경험 정리를 개별 조회합니다. 현재 경험 정리의 상태를 반환합니다. (대화 중/완료)
 * @summary 경험 정리 개별 조회
 */
export type experienceControllerGetExperienceResponse200 = {
  data: ExperienceControllerGetExperience200
  status: 200
}

export type experienceControllerGetExperienceResponse401 = {
  data: CommonResponse
  status: 401
}

export type experienceControllerGetExperienceResponse404 = {
  data: CommonResponse
  status: 404
}

export type experienceControllerGetExperienceResponseSuccess = (experienceControllerGetExperienceResponse200) & {
  headers: Headers;
};
export type experienceControllerGetExperienceResponseError = (experienceControllerGetExperienceResponse401 | experienceControllerGetExperienceResponse404) & {
  headers: Headers;
};

export type experienceControllerGetExperienceResponse = (experienceControllerGetExperienceResponseSuccess | experienceControllerGetExperienceResponseError)

export const getExperienceControllerGetExperienceUrl = (experienceId: number,) => {


  

  return `/experiences/${experienceId}`
}

export const experienceControllerGetExperience = async (experienceId: number, options?: RequestInit): Promise<experienceControllerGetExperienceResponse> => {
  
  return customInstance<experienceControllerGetExperienceResponse>(getExperienceControllerGetExperienceUrl(experienceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getExperienceControllerGetExperienceQueryKey = (experienceId: number,) => {
    return [
    `/experiences/${experienceId}`
    ] as const;
    }

    
export const getExperienceControllerGetExperienceQueryOptions = <TData = Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError = CommonResponse>(experienceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExperienceControllerGetExperienceQueryKey(experienceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof experienceControllerGetExperience>>> = ({ signal }) => experienceControllerGetExperience(experienceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(experienceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExperienceControllerGetExperienceQueryResult = NonNullable<Awaited<ReturnType<typeof experienceControllerGetExperience>>>
export type ExperienceControllerGetExperienceQueryError = CommonResponse


export function useExperienceControllerGetExperience<TData = Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError = CommonResponse>(
 experienceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceControllerGetExperience>>,
          TError,
          Awaited<ReturnType<typeof experienceControllerGetExperience>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceControllerGetExperience<TData = Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError = CommonResponse>(
 experienceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceControllerGetExperience>>,
          TError,
          Awaited<ReturnType<typeof experienceControllerGetExperience>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceControllerGetExperience<TData = Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError = CommonResponse>(
 experienceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 경험 정리 개별 조회
 */

export function useExperienceControllerGetExperience<TData = Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError = CommonResponse>(
 experienceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceControllerGetExperience>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExperienceControllerGetExperienceQueryOptions(experienceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 경험 정리의 제목 또는 희망 직무를 수정합니다.
 * @summary 경험 정리 수정
 */
export type experienceControllerUpdateExperienceResponse200 = {
  data: ExperienceControllerUpdateExperience200
  status: 200
}

export type experienceControllerUpdateExperienceResponse401 = {
  data: CommonResponse
  status: 401
}

export type experienceControllerUpdateExperienceResponse404 = {
  data: CommonResponse
  status: 404
}

export type experienceControllerUpdateExperienceResponse409 = {
  data: CommonResponse
  status: 409
}

export type experienceControllerUpdateExperienceResponseSuccess = (experienceControllerUpdateExperienceResponse200) & {
  headers: Headers;
};
export type experienceControllerUpdateExperienceResponseError = (experienceControllerUpdateExperienceResponse401 | experienceControllerUpdateExperienceResponse404 | experienceControllerUpdateExperienceResponse409) & {
  headers: Headers;
};

export type experienceControllerUpdateExperienceResponse = (experienceControllerUpdateExperienceResponseSuccess | experienceControllerUpdateExperienceResponseError)

export const getExperienceControllerUpdateExperienceUrl = (experienceId: number,) => {


  

  return `/experiences/${experienceId}`
}

export const experienceControllerUpdateExperience = async (experienceId: number,
    updateExperienceReqDTO: UpdateExperienceReqDTO, options?: RequestInit): Promise<experienceControllerUpdateExperienceResponse> => {
  
  return customInstance<experienceControllerUpdateExperienceResponse>(getExperienceControllerUpdateExperienceUrl(experienceId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateExperienceReqDTO,)
  }
);}
  



export const getExperienceControllerUpdateExperienceMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceControllerUpdateExperience>>, TError,{experienceId: number;data: UpdateExperienceReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof experienceControllerUpdateExperience>>, TError,{experienceId: number;data: UpdateExperienceReqDTO}, TContext> => {

const mutationKey = ['experienceControllerUpdateExperience'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof experienceControllerUpdateExperience>>, {experienceId: number;data: UpdateExperienceReqDTO}> = (props) => {
          const {experienceId,data} = props ?? {};

          return  experienceControllerUpdateExperience(experienceId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExperienceControllerUpdateExperienceMutationResult = NonNullable<Awaited<ReturnType<typeof experienceControllerUpdateExperience>>>
    export type ExperienceControllerUpdateExperienceMutationBody = UpdateExperienceReqDTO
    export type ExperienceControllerUpdateExperienceMutationError = CommonResponse

    /**
 * @summary 경험 정리 수정
 */
export const useExperienceControllerUpdateExperience = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceControllerUpdateExperience>>, TError,{experienceId: number;data: UpdateExperienceReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof experienceControllerUpdateExperience>>,
        TError,
        {experienceId: number;data: UpdateExperienceReqDTO},
        TContext
      > => {
      return useMutation(getExperienceControllerUpdateExperienceMutationOptions(options), queryClient);
    }
    