/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponse,
  CreateCorrectionReqDTO,
  MapCorrectionWithPortfoliosReqDTO,
  PortfolioCorrectionControllerCreateCompanyInsight200,
  PortfolioCorrectionControllerCreateCorrection200,
  PortfolioCorrectionControllerCreateCorrectionByAI200,
  PortfolioCorrectionControllerDeleteCorrection200,
  PortfolioCorrectionControllerGetCompanyInsight200,
  PortfolioCorrectionControllerGetCorrection200,
  PortfolioCorrectionControllerGetCorrectionStatus200,
  PortfolioCorrectionControllerGetCorrections200,
  PortfolioCorrectionControllerGetCorrectionsParams,
  PortfolioCorrectionControllerMapCorrectionWithPortfolios200,
  PortfolioCorrectionControllerUpdateCompanyInsight200,
  PortfolioCorrectionControllerUpdateCorrectionTitle200,
  UpdateCompanyInsightReqDTO,
  UpdateCorrectionTitleReqDTO
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 포트폴리오 첨삭 목록을 조회합니다. 검색어를 입력하면 제목에 키워드를 포함하는 목록만 조회됩니다.
 * @summary 첨삭 목록 조회
 */
export const portfolioCorrectionControllerGetCorrections = (
    params?: PortfolioCorrectionControllerGetCorrectionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerGetCorrections200>(
      {url: `/portfolio-corrections`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPortfolioCorrectionControllerGetCorrectionsQueryKey = (params?: PortfolioCorrectionControllerGetCorrectionsParams,) => {
    return [
    `/portfolio-corrections`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getPortfolioCorrectionControllerGetCorrectionsQueryOptions = <TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError = CommonResponse>(params?: PortfolioCorrectionControllerGetCorrectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioCorrectionControllerGetCorrectionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>> = ({ signal }) => portfolioCorrectionControllerGetCorrections(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PortfolioCorrectionControllerGetCorrectionsQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>>
export type PortfolioCorrectionControllerGetCorrectionsQueryError = CommonResponse


export function usePortfolioCorrectionControllerGetCorrections<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError = CommonResponse>(
 params: undefined |  PortfolioCorrectionControllerGetCorrectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrections<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError = CommonResponse>(
 params?: PortfolioCorrectionControllerGetCorrectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrections<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError = CommonResponse>(
 params?: PortfolioCorrectionControllerGetCorrectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 첨삭 목록 조회
 */

export function usePortfolioCorrectionControllerGetCorrections<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError = CommonResponse>(
 params?: PortfolioCorrectionControllerGetCorrectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPortfolioCorrectionControllerGetCorrectionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 포트폴리오 첨삭을 시작합니다. 포트폴리오 첨삭 티켓 1장이 사용됩니다.
 * @summary 첨삭 의뢰하기
 */
export const portfolioCorrectionControllerCreateCorrection = (
    createCorrectionReqDTO: CreateCorrectionReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerCreateCorrection200>(
      {url: `/portfolio-corrections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCorrectionReqDTO, signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerCreateCorrectionMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>, TError,{data: CreateCorrectionReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>, TError,{data: CreateCorrectionReqDTO}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerCreateCorrection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>, {data: CreateCorrectionReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  portfolioCorrectionControllerCreateCorrection(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerCreateCorrectionMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>>
    export type PortfolioCorrectionControllerCreateCorrectionMutationBody = CreateCorrectionReqDTO
    export type PortfolioCorrectionControllerCreateCorrectionMutationError = CommonResponse

    /**
 * @summary 첨삭 의뢰하기
 */
export const usePortfolioCorrectionControllerCreateCorrection = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>, TError,{data: CreateCorrectionReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrection>>,
        TError,
        {data: CreateCorrectionReqDTO},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerCreateCorrectionMutationOptions(options), queryClient);
    }
    /**
 * 특정 AI 첨삭의 진행 상태를 조회합니다.
 * @summary 개별 첨삭 상태 조회
 */
export const portfolioCorrectionControllerGetCorrectionStatus = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerGetCorrectionStatus200>(
      {url: `/portfolio-corrections/${correctionId}/status`, method: 'GET', signal
    },
      options);
    }
  



export const getPortfolioCorrectionControllerGetCorrectionStatusQueryKey = (correctionId: number,) => {
    return [
    `/portfolio-corrections/${correctionId}/status`
    ] as const;
    }

    
export const getPortfolioCorrectionControllerGetCorrectionStatusQueryOptions = <TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError = CommonResponse>(correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioCorrectionControllerGetCorrectionStatusQueryKey(correctionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>> = ({ signal }) => portfolioCorrectionControllerGetCorrectionStatus(correctionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(correctionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PortfolioCorrectionControllerGetCorrectionStatusQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>>
export type PortfolioCorrectionControllerGetCorrectionStatusQueryError = CommonResponse


export function usePortfolioCorrectionControllerGetCorrectionStatus<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError = CommonResponse>(
 correctionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrectionStatus<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrectionStatus<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 개별 첨삭 상태 조회
 */

export function usePortfolioCorrectionControllerGetCorrectionStatus<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrectionStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPortfolioCorrectionControllerGetCorrectionStatusQueryOptions(correctionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 특정 AI 첨삭의 기업 분석 정보 생성을 시작합니다.
 * @summary 기업 분석 정보 생성
 */
export const portfolioCorrectionControllerCreateCompanyInsight = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerCreateCompanyInsight200>(
      {url: `/portfolio-corrections/${correctionId}/company-insight`, method: 'POST', signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerCreateCompanyInsightMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>, TError,{correctionId: number}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerCreateCompanyInsight'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>, {correctionId: number}> = (props) => {
          const {correctionId} = props ?? {};

          return  portfolioCorrectionControllerCreateCompanyInsight(correctionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerCreateCompanyInsightMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>>
    
    export type PortfolioCorrectionControllerCreateCompanyInsightMutationError = CommonResponse

    /**
 * @summary 기업 분석 정보 생성
 */
export const usePortfolioCorrectionControllerCreateCompanyInsight = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCompanyInsight>>,
        TError,
        {correctionId: number},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerCreateCompanyInsightMutationOptions(options), queryClient);
    }
    /**
 * 특정 AI 첨삭의 기업 분석 정보를 조회합니다.
 * @summary 기업 분석 정보 조회
 */
export const portfolioCorrectionControllerGetCompanyInsight = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerGetCompanyInsight200>(
      {url: `/portfolio-corrections/${correctionId}/company-insight`, method: 'GET', signal
    },
      options);
    }
  



export const getPortfolioCorrectionControllerGetCompanyInsightQueryKey = (correctionId: number,) => {
    return [
    `/portfolio-corrections/${correctionId}/company-insight`
    ] as const;
    }

    
export const getPortfolioCorrectionControllerGetCompanyInsightQueryOptions = <TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError = CommonResponse>(correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioCorrectionControllerGetCompanyInsightQueryKey(correctionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>> = ({ signal }) => portfolioCorrectionControllerGetCompanyInsight(correctionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(correctionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PortfolioCorrectionControllerGetCompanyInsightQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>>
export type PortfolioCorrectionControllerGetCompanyInsightQueryError = CommonResponse


export function usePortfolioCorrectionControllerGetCompanyInsight<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError = CommonResponse>(
 correctionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCompanyInsight<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCompanyInsight<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 기업 분석 정보 조회
 */

export function usePortfolioCorrectionControllerGetCompanyInsight<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCompanyInsight>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPortfolioCorrectionControllerGetCompanyInsightQueryOptions(correctionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * AI가 생성한 기업 분석 정보를 사용자가 수정합니다. 또는 강조 포인트를 추가합니다.
 * @summary 기업 분석 정보 수정
 */
export const portfolioCorrectionControllerUpdateCompanyInsight = (
    correctionId: number,
    updateCompanyInsightReqDTO: UpdateCompanyInsightReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerUpdateCompanyInsight200>(
      {url: `/portfolio-corrections/${correctionId}/company-insight`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCompanyInsightReqDTO, signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerUpdateCompanyInsightMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>, TError,{correctionId: number;data: UpdateCompanyInsightReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>, TError,{correctionId: number;data: UpdateCompanyInsightReqDTO}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerUpdateCompanyInsight'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>, {correctionId: number;data: UpdateCompanyInsightReqDTO}> = (props) => {
          const {correctionId,data} = props ?? {};

          return  portfolioCorrectionControllerUpdateCompanyInsight(correctionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerUpdateCompanyInsightMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>>
    export type PortfolioCorrectionControllerUpdateCompanyInsightMutationBody = UpdateCompanyInsightReqDTO
    export type PortfolioCorrectionControllerUpdateCompanyInsightMutationError = CommonResponse

    /**
 * @summary 기업 분석 정보 수정
 */
export const usePortfolioCorrectionControllerUpdateCompanyInsight = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>, TError,{correctionId: number;data: UpdateCompanyInsightReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCompanyInsight>>,
        TError,
        {correctionId: number;data: UpdateCompanyInsightReqDTO},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerUpdateCompanyInsightMutationOptions(options), queryClient);
    }
    /**
 * 첨삭을 진행할 포트폴리오를 선택하고 매핑 테이블에서 활성화합니다.
 * @summary 포트폴리오 선택
 */
export const portfolioCorrectionControllerMapCorrectionWithPortfolios = (
    correctionId: number,
    mapCorrectionWithPortfoliosReqDTO: MapCorrectionWithPortfoliosReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerMapCorrectionWithPortfolios200>(
      {url: `/portfolio-corrections/${correctionId}/select`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mapCorrectionWithPortfoliosReqDTO, signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerMapCorrectionWithPortfoliosMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>, TError,{correctionId: number;data: MapCorrectionWithPortfoliosReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>, TError,{correctionId: number;data: MapCorrectionWithPortfoliosReqDTO}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerMapCorrectionWithPortfolios'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>, {correctionId: number;data: MapCorrectionWithPortfoliosReqDTO}> = (props) => {
          const {correctionId,data} = props ?? {};

          return  portfolioCorrectionControllerMapCorrectionWithPortfolios(correctionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerMapCorrectionWithPortfoliosMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>>
    export type PortfolioCorrectionControllerMapCorrectionWithPortfoliosMutationBody = MapCorrectionWithPortfoliosReqDTO
    export type PortfolioCorrectionControllerMapCorrectionWithPortfoliosMutationError = CommonResponse

    /**
 * @summary 포트폴리오 선택
 */
export const usePortfolioCorrectionControllerMapCorrectionWithPortfolios = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>, TError,{correctionId: number;data: MapCorrectionWithPortfoliosReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerMapCorrectionWithPortfolios>>,
        TError,
        {correctionId: number;data: MapCorrectionWithPortfoliosReqDTO},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerMapCorrectionWithPortfoliosMutationOptions(options), queryClient);
    }
    /**
 * 요청 본문 없이 활성화된 포트폴리오 매핑을 기준으로 AI 첨삭 생성 준비를 수행합니다.
 * @summary AI 첨삭 생성
 */
export const portfolioCorrectionControllerCreateCorrectionByAI = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerCreateCorrectionByAI200>(
      {url: `/portfolio-corrections/${correctionId}/generate`, method: 'POST', signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerCreateCorrectionByAIMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>, TError,{correctionId: number}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerCreateCorrectionByAI'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>, {correctionId: number}> = (props) => {
          const {correctionId} = props ?? {};

          return  portfolioCorrectionControllerCreateCorrectionByAI(correctionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerCreateCorrectionByAIMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>>
    
    export type PortfolioCorrectionControllerCreateCorrectionByAIMutationError = CommonResponse

    /**
 * @summary AI 첨삭 생성
 */
export const usePortfolioCorrectionControllerCreateCorrectionByAI = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerCreateCorrectionByAI>>,
        TError,
        {correctionId: number},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerCreateCorrectionByAIMutationOptions(options), queryClient);
    }
    /**
 * 특정 AI 첨삭의 결과를 조회합니다.
 * @summary 개별 첨삭 조회
 */
export const portfolioCorrectionControllerGetCorrection = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerGetCorrection200>(
      {url: `/portfolio-corrections/${correctionId}`, method: 'GET', signal
    },
      options);
    }
  



export const getPortfolioCorrectionControllerGetCorrectionQueryKey = (correctionId: number,) => {
    return [
    `/portfolio-corrections/${correctionId}`
    ] as const;
    }

    
export const getPortfolioCorrectionControllerGetCorrectionQueryOptions = <TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError = CommonResponse>(correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioCorrectionControllerGetCorrectionQueryKey(correctionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>> = ({ signal }) => portfolioCorrectionControllerGetCorrection(correctionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(correctionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PortfolioCorrectionControllerGetCorrectionQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>>
export type PortfolioCorrectionControllerGetCorrectionQueryError = CommonResponse


export function usePortfolioCorrectionControllerGetCorrection<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError = CommonResponse>(
 correctionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrection<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>,
          TError,
          Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePortfolioCorrectionControllerGetCorrection<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 개별 첨삭 조회
 */

export function usePortfolioCorrectionControllerGetCorrection<TData = Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError = CommonResponse>(
 correctionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerGetCorrection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPortfolioCorrectionControllerGetCorrectionQueryOptions(correctionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 특정 AI 첨삭의 제목을 수정합니다.
 * @summary 개별 첨삭 수정
 */
export const portfolioCorrectionControllerUpdateCorrectionTitle = (
    correctionId: number,
    updateCorrectionTitleReqDTO: UpdateCorrectionTitleReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerUpdateCorrectionTitle200>(
      {url: `/portfolio-corrections/${correctionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCorrectionTitleReqDTO, signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerUpdateCorrectionTitleMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>, TError,{correctionId: number;data: UpdateCorrectionTitleReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>, TError,{correctionId: number;data: UpdateCorrectionTitleReqDTO}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerUpdateCorrectionTitle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>, {correctionId: number;data: UpdateCorrectionTitleReqDTO}> = (props) => {
          const {correctionId,data} = props ?? {};

          return  portfolioCorrectionControllerUpdateCorrectionTitle(correctionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerUpdateCorrectionTitleMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>>
    export type PortfolioCorrectionControllerUpdateCorrectionTitleMutationBody = UpdateCorrectionTitleReqDTO
    export type PortfolioCorrectionControllerUpdateCorrectionTitleMutationError = CommonResponse

    /**
 * @summary 개별 첨삭 수정
 */
export const usePortfolioCorrectionControllerUpdateCorrectionTitle = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>, TError,{correctionId: number;data: UpdateCorrectionTitleReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerUpdateCorrectionTitle>>,
        TError,
        {correctionId: number;data: UpdateCorrectionTitleReqDTO},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerUpdateCorrectionTitleMutationOptions(options), queryClient);
    }
    /**
 * AI 첨삭 내역을 삭제합니다.
 * @summary 첨삭 삭제하기
 */
export const portfolioCorrectionControllerDeleteCorrection = (
    correctionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortfolioCorrectionControllerDeleteCorrection200>(
      {url: `/portfolio-corrections/${correctionId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getPortfolioCorrectionControllerDeleteCorrectionMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>, TError,{correctionId: number}, TContext> => {

const mutationKey = ['portfolioCorrectionControllerDeleteCorrection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>, {correctionId: number}> = (props) => {
          const {correctionId} = props ?? {};

          return  portfolioCorrectionControllerDeleteCorrection(correctionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioCorrectionControllerDeleteCorrectionMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>>
    
    export type PortfolioCorrectionControllerDeleteCorrectionMutationError = CommonResponse

    /**
 * @summary 첨삭 삭제하기
 */
export const usePortfolioCorrectionControllerDeleteCorrection = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>, TError,{correctionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof portfolioCorrectionControllerDeleteCorrection>>,
        TError,
        {correctionId: number},
        TContext
      > => {
      return useMutation(getPortfolioCorrectionControllerDeleteCorrectionMutationOptions(options), queryClient);
    }
    