/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommitReqDTO,
  CommonResponse,
  ExperienceMapInternalControllerCommit200,
  ExperienceMapInternalControllerGetCommitStatus200,
  ExperienceMapInternalControllerGetTemplates200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * AI 서버가 기동 시 1회 조회 후 1시간 TTL로 캐시한다. unknown_slot_id(422) 응답을 받으면 즉시 재조회한다. 문구가 바뀌면 version이 갱신된다.
 * @summary 블록 템플릿 카탈로그 조회 (AI 서버용)
 */
export const experienceMapInternalControllerGetTemplates = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ExperienceMapInternalControllerGetTemplates200>(
      {url: `/api/v1/experience-map/templates`, method: 'GET', signal
    },
      options);
    }
  



export const getExperienceMapInternalControllerGetTemplatesQueryKey = () => {
    return [
    `/api/v1/experience-map/templates`
    ] as const;
    }

    
export const getExperienceMapInternalControllerGetTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError = CommonResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExperienceMapInternalControllerGetTemplatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>> = ({ signal }) => experienceMapInternalControllerGetTemplates(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExperienceMapInternalControllerGetTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>>
export type ExperienceMapInternalControllerGetTemplatesQueryError = CommonResponse


export function useExperienceMapInternalControllerGetTemplates<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError = CommonResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>,
          TError,
          Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceMapInternalControllerGetTemplates<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>,
          TError,
          Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceMapInternalControllerGetTemplates<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 블록 템플릿 카탈로그 조회 (AI 서버용)
 */

export function useExperienceMapInternalControllerGetTemplates<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError = CommonResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExperienceMapInternalControllerGetTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 경험 맵 쓰기는 이 API 하나로 모인다. (user_id, request_id) 기준으로 멱등하며, 이미 커밋된 요청은 재실행하지 않고 저장된 결과를 그대로 반환한다. base_map_version이 현재 값과 다르면 409(map_version_conflict)로 거부한다.
 * @summary 경험 맵 커밋 (AI 서버용)
 */
export const experienceMapInternalControllerCommit = (
    commitReqDTO: CommitReqDTO,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ExperienceMapInternalControllerCommit200>(
      {url: `/api/v1/experience-map/commit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commitReqDTO, signal
    },
      options);
    }
  


export const getExperienceMapInternalControllerCommitMutationOptions = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>, TError,{data: CommitReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>, TError,{data: CommitReqDTO}, TContext> => {

const mutationKey = ['experienceMapInternalControllerCommit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>, {data: CommitReqDTO}> = (props) => {
          const {data} = props ?? {};

          return  experienceMapInternalControllerCommit(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExperienceMapInternalControllerCommitMutationResult = NonNullable<Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>>
    export type ExperienceMapInternalControllerCommitMutationBody = CommitReqDTO
    export type ExperienceMapInternalControllerCommitMutationError = CommonResponse

    /**
 * @summary 경험 맵 커밋 (AI 서버용)
 */
export const useExperienceMapInternalControllerCommit = <TError = CommonResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>, TError,{data: CommitReqDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof experienceMapInternalControllerCommit>>,
        TError,
        {data: CommitReqDTO},
        TContext
      > => {
      return useMutation(getExperienceMapInternalControllerCommitMutationOptions(options), queryClient);
    }
    /**
 * AI 서버가 커밋 응답을 받기 전에 죽었을 때 실제로 커밋됐는지 확인한다. committed=false면 재커밋할 수 있다는 뜻이다.
 * @summary 커밋 결과 조회 (AI 서버 크래시 복구용)
 */
export const experienceMapInternalControllerGetCommitStatus = (
    requestId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ExperienceMapInternalControllerGetCommitStatus200>(
      {url: `/api/v1/experience-map/commit/${requestId}`, method: 'GET', signal
    },
      options);
    }
  



export const getExperienceMapInternalControllerGetCommitStatusQueryKey = (requestId: string,) => {
    return [
    `/api/v1/experience-map/commit/${requestId}`
    ] as const;
    }

    
export const getExperienceMapInternalControllerGetCommitStatusQueryOptions = <TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError = CommonResponse>(requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExperienceMapInternalControllerGetCommitStatusQueryKey(requestId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>> = ({ signal }) => experienceMapInternalControllerGetCommitStatus(requestId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(requestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExperienceMapInternalControllerGetCommitStatusQueryResult = NonNullable<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>>
export type ExperienceMapInternalControllerGetCommitStatusQueryError = CommonResponse


export function useExperienceMapInternalControllerGetCommitStatus<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError = CommonResponse>(
 requestId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>,
          TError,
          Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceMapInternalControllerGetCommitStatus<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError = CommonResponse>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>,
          TError,
          Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExperienceMapInternalControllerGetCommitStatus<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError = CommonResponse>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 커밋 결과 조회 (AI 서버 크래시 복구용)
 */

export function useExperienceMapInternalControllerGetCommitStatus<TData = Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError = CommonResponse>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof experienceMapInternalControllerGetCommitStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExperienceMapInternalControllerGetCommitStatusQueryOptions(requestId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




