/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface ActivityNameReqDTO {
  /**
   * 활동 태그 이름
   * @minLength 1
   * @maxLength 20
   */
  name: string;
}
