/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 가장 최근 요청의 상태. running=처리 중, completed=완료, failed=실패(처리 중 서버가 죽은 경우 포함), cancelled=사용자가 중지
 */
export type ActivityStatusResDTOStatus = typeof ActivityStatusResDTOStatus[keyof typeof ActivityStatusResDTOStatus];


export const ActivityStatusResDTOStatus = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
