/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserItemResDTOEmail } from './adminUserItemResDTOEmail';
import type { AdminUserItemResDTOLoginType } from './adminUserItemResDTOLoginType';
import type { AdminUserItemResDTOPhoneNum } from './adminUserItemResDTOPhoneNum';

export interface AdminUserItemResDTO {
  userId: number;
  name: string;
  /** @nullable */
  email?: AdminUserItemResDTOEmail;
  /** @nullable */
  loginType?: AdminUserItemResDTOLoginType;
  /** @nullable */
  phoneNum?: AdminUserItemResDTOPhoneNum;
  isActive: boolean;
  /** 잔여 경험 정리 이용권 수량 */
  experienceTickets: number;
  /** 잔여 포트폴리오 첨삭 이용권 수량 */
  correctionTickets: number;
}
