/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type AdminGrantRewardResDTORewardStatus = typeof AdminGrantRewardResDTORewardStatus[keyof typeof AdminGrantRewardResDTORewardStatus];


export const AdminGrantRewardResDTORewardStatus = {
  NOT_GRANTED: 'NOT_GRANTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  GRANTED: 'GRANTED',
  REJECTED: 'REJECTED',
} as const;
