/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type AdminEventRewardControllerSearchUsersParams = {
/**
 * 검색 키워드 (이름 또는 이메일)
 * @maxLength 100
 */
keyword?: string;
};
