/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEventRewardControllerSearchUsers200Error } from './adminEventRewardControllerSearchUsers200Error';
import type { AdminUserSearchResDTO } from './adminUserSearchResDTO';

export type AdminEventRewardControllerSearchUsers200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: AdminEventRewardControllerSearchUsers200Error;
  result?: AdminUserSearchResDTO;
};
