/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEventRewardControllerGetTicketGrants200Error } from './adminEventRewardControllerGetTicketGrants200Error';
import type { AdminTicketGrantListResDTO } from './adminTicketGrantListResDTO';

export type AdminEventRewardControllerGetTicketGrants200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: AdminEventRewardControllerGetTicketGrants200Error;
  result?: AdminTicketGrantListResDTO;
};
