/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CustomRewardItemDTO } from './customRewardItemDTO';

export interface AdminGrantRewardReqDTO {
  /**
   * 보상 대상 사용자 ID
   * @minimum 1
   */
  userId: number;
  /**
   * 검토자 식별자
   * @maxLength 64
   */
  reviewedBy?: string;
  /**
   * 검토 메모
   * @maxLength 500
   */
  reviewNote?: string;
  /** 커스텀 보상 (allowMultipleRewards 이벤트 전용, 미지정 시 이벤트 rewardConfig 사용) */
  customRewards?: CustomRewardItemDTO[];
}
