/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 마케팅 수신 동의 시각 (비동의 상태면 null)
 * @nullable
 */
export type AgreeMarketingResDTOMarketingAgreedAt = { [key: string]: unknown } | null;
