/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AppControllerGetHello200Error } from './appControllerGetHello200Error';
import type { AppControllerGetHello200Result } from './appControllerGetHello200Result';

export type AppControllerGetHello200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: AppControllerGetHello200Error;
  result?: AppControllerGetHello200Result;
};
