/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 특성별 성향 점수 (레이더 차트용)
 */
export type AssessmentResultResDTOTraitVector = typeof AssessmentResultResDTOTraitVector[keyof typeof AssessmentResultResDTOTraitVector];


export const AssessmentResultResDTOTraitVector = {
  INVESTIGATIVE: 'INVESTIGATIVE',
  SOCIAL: 'SOCIAL',
  ENTERPRISING: 'ENTERPRISING',
  CONVENTIONAL: 'CONVENTIONAL',
  REALISTIC: 'REALISTIC',
  ARTISTIC: 'ARTISTIC',
} as const;
