/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentStatusResDTOUuid } from './assessmentStatusResDTOUuid';

export interface AssessmentStatusResDTO {
  /** 이 계정으로 완료(생성 또는 claim)한 분석 결과가 있는지 여부 */
  hasCompleted: boolean;
  /**
   * 가장 최근 결과의 uuid(조회/공유용). 없으면 null
   * @nullable
   */
  uuid: AssessmentStatusResDTOUuid;
}
