/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentControllerGetStatus200Error } from './assessmentControllerGetStatus200Error';
import type { AssessmentStatusResDTO } from './assessmentStatusResDTO';

export type AssessmentControllerGetStatus200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: AssessmentControllerGetStatus200Error;
  result?: AssessmentStatusResDTO;
};
