/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AuthControllerHandleLogout200Error } from './authControllerHandleLogout200Error';
import type { AuthControllerHandleLogout200Result } from './authControllerHandleLogout200Result';

export type AuthControllerHandleLogout200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: AuthControllerHandleLogout200Error;
  result?: AuthControllerHandleLogout200Result;
};
