/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { BlockResDTOKind } from './blockResDTOKind';
import type { ExperienceMetaResDTO } from './experienceMetaResDTO';

export interface BlockResDTO {
  /** bigint라 JS number 정밀도(2^53) 초과를 피하기 위해 문자열로 반환한다. */
  id: string;
  /**
   * bigint라 문자열로 반환한다. 1단계(루트) 블록은 null.
   * @nullable
   */
  parentId: string | null;
  kind: BlockResDTOKind;
  experienceMeta?: ExperienceMetaResDTO;
  children: BlockResDTO[];
  level: number;
  position: number;
  /** @nullable */
  content: string | null;
  /** @nullable */
  placeholder: string | null;
  createdAt: string;
  updatedAt: string;
}
