/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type ClaimEventRewardResDTORewardStatus = typeof ClaimEventRewardResDTORewardStatus[keyof typeof ClaimEventRewardResDTORewardStatus];


export const ClaimEventRewardResDTORewardStatus = {
  NOT_GRANTED: 'NOT_GRANTED',
  GRANTED: 'GRANTED',
} as const;
