/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CommitAppliedItemResDTO } from './commitAppliedItemResDTO';

export interface CommitResDTO {
  request_id: string;
  previous_version: number;
  map_version: number;
  applied: CommitAppliedItemResDTO[];
}
