/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 같은 요청에서 앞서 정의한 add item을 부모로 쓸 때. 부모가 자식보다 먼저 나와야 한다.
 * @nullable
 */
export type CommitItemReqDTOParentItemId = { [key: string]: unknown } | null;
