/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 결과 데이터
 * @nullable
 */
export type CommonResponseResult = { [key: string]: unknown } | null;
