/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CommitItemReqDTO } from './commitItemReqDTO';

export interface CommitReqDTO {
  user_id: string;
  request_id: string;
  base_map_version: number;
  /** @minItems 1 */
  items: CommitItemReqDTO[];
}
