/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type CommitAppliedItemResDTOAction = typeof CommitAppliedItemResDTOAction[keyof typeof CommitAppliedItemResDTOAction];


export const CommitAppliedItemResDTOAction = {
  add: 'add',
  update: 'update',
  delete: 'delete',
} as const;
