/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface CompletionSummaryDTO {
  /** 완료된 슬라이드 수 */
  completed: number;
  /** 실패한 슬라이드 수 */
  failed: number;
}
