/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 담당업무 첨삭 결과
 */
export type CorrectionResultItemReqDTOResponsibilities = { [key: string]: unknown };
