/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type CorrectionStatusResDTOStatus = typeof CorrectionStatusResDTOStatus[keyof typeof CorrectionStatusResDTOStatus];


export const CorrectionStatusResDTOStatus = {
  DONE: 'DONE',
  NOT_STARTED: 'NOT_STARTED',
  DOING_RAG: 'DOING_RAG',
  COMPANY_INSIGHT: 'COMPANY_INSIGHT',
  GENERATING: 'GENERATING',
} as const;
