/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CreateExperienceReqDTOHopeJob } from './createExperienceReqDTOHopeJob';

export interface CreateExperienceReqDTO {
  /**
   * @minLength 1
   * @maxLength 20
   */
  name: string;
  hopeJob: CreateExperienceReqDTOHopeJob;
}
