/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCorrectionReqDTOJobDescriptionType } from './createCorrectionReqDTOJobDescriptionType';

export interface CreateCorrectionReqDTO {
  /**
   * 첨삭 제목
   * @minLength 1
   * @maxLength 20
   */
  title: string;
  /**
   * 지원 회사명
   * @minLength 1
   * @maxLength 20
   */
  companyName: string;
  /**
   * 지원 포지션명
   * @minLength 1
   * @maxLength 20
   */
  positionName: string;
  /**
   * 채용 공고 또는 직무 설명
   * @maxLength 700
   */
  jobDescription?: string;
  jobDescriptionType: CreateCorrectionReqDTOJobDescriptionType;
}
