/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CustomRewardItemDTOType } from './customRewardItemDTOType';

export interface CustomRewardItemDTO {
  /** 이용권 종류 */
  type: CustomRewardItemDTOType;
  /**
   * 수량 (1~10)
   * @minimum 1
   * @maximum 10
   */
  quantity: number;
}
