/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { EventControllerGetFeedbackModal200Error } from './eventControllerGetFeedbackModal200Error';
import type { FeedbackModalResDTO } from './feedbackModalResDTO';

export type EventControllerGetFeedbackModal200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: EventControllerGetFeedbackModal200Error;
  result?: FeedbackModalResDTO;
};
