/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ClaimEventRewardResDTO } from './claimEventRewardResDTO';
import type { EventControllerClaimEventReward200Error } from './eventControllerClaimEventReward200Error';

export type EventControllerClaimEventReward200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: EventControllerClaimEventReward200Error;
  result?: ClaimEventRewardResDTO;
};
