/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { EventProgressCardResDTOCtaLink } from './eventProgressCardResDTOCtaLink';
import type { EventProgressCardResDTORewardStatus } from './eventProgressCardResDTORewardStatus';

export interface EventProgressCardResDTO {
  eventCode: string;
  title: string;
  subtitle: string;
  content: string;
  progress: number;
  target: number;
  remaining: number;
  isCompleted: boolean;
  rewardStatus: EventProgressCardResDTORewardStatus;
  ctaText: string;
  /** @nullable */
  ctaLink?: EventProgressCardResDTOCtaLink;
}
