/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 등록된 폼이 없으면 null
 * @nullable
 */
export type EventFeedbackFormResDTOFormId = { [key: string]: unknown } | null;
