/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExperienceMapAiControllerGetUsage200Error } from './experienceMapAiControllerGetUsage200Error';
import type { UsageResDTO } from './usageResDTO';

export type ExperienceMapAiControllerGetUsage200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: ExperienceMapAiControllerGetUsage200Error;
  result?: UsageResDTO;
};
