/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExperienceMapControllerDeleteBlock200Error } from './experienceMapControllerDeleteBlock200Error';
import type { ExperienceMapControllerDeleteBlock200Result } from './experienceMapControllerDeleteBlock200Result';

export type ExperienceMapControllerDeleteBlock200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: ExperienceMapControllerDeleteBlock200Error;
  result?: ExperienceMapControllerDeleteBlock200Result;
};
