/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type ExperienceStateResDTOStatus = typeof ExperienceStateResDTOStatus[keyof typeof ExperienceStateResDTOStatus];


export const ExperienceStateResDTOStatus = {
  ON_CHAT: 'ON_CHAT',
  GENERATE: 'GENERATE',
  DONE: 'DONE',
} as const;
