/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type ExperienceStateResDTOHopeJob = typeof ExperienceStateResDTOHopeJob[keyof typeof ExperienceStateResDTOHopeJob];


export const ExperienceStateResDTOHopeJob = {
  NONE: 'NONE',
  PLANNING: 'PLANNING',
  MARKETING: 'MARKETING',
  DESIGN: 'DESIGN',
  DEV: 'DEV',
  MEDIA: 'MEDIA',
  DATA: 'DATA',
} as const;
