/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExperienceMapInternalControllerMarkRequestFailed200Error } from './experienceMapInternalControllerMarkRequestFailed200Error';
import type { ExperienceMapInternalControllerMarkRequestFailed200Result } from './experienceMapInternalControllerMarkRequestFailed200Result';

export type ExperienceMapInternalControllerMarkRequestFailed200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: ExperienceMapInternalControllerMarkRequestFailed200Error;
  result?: ExperienceMapInternalControllerMarkRequestFailed200Result;
};
