/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalPortfolioControllerCreateExternalPortfolioBlock200Error } from './externalPortfolioControllerCreateExternalPortfolioBlock200Error';
import type { StructuredPortfolioResDTO } from './structuredPortfolioResDTO';

export type ExternalPortfolioControllerCreateExternalPortfolioBlock200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: ExternalPortfolioControllerCreateExternalPortfolioBlock200Error;
  result?: StructuredPortfolioResDTO;
};
