/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalPortfolioListResDTOOriginalFileName } from './externalPortfolioListResDTOOriginalFileName';
import type { ExternalPortfolioListResDTOStatus } from './externalPortfolioListResDTOStatus';
import type { StructuredPortfolioResDTO } from './structuredPortfolioResDTO';

export interface ExternalPortfolioListResDTO {
  status: ExternalPortfolioListResDTOStatus;
  /** @nullable */
  originalFileName: ExternalPortfolioListResDTOOriginalFileName;
  portfolios: StructuredPortfolioResDTO[];
}
