/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalPortfolioControllerGetExternalPortfolios200Error } from './externalPortfolioControllerGetExternalPortfolios200Error';
import type { StructuredPortfolioResDTO } from './structuredPortfolioResDTO';

export type ExternalPortfolioControllerGetExternalPortfolios200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: ExternalPortfolioControllerGetExternalPortfolios200Error;
  result?: StructuredPortfolioResDTO[];
};
