/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type FeedbackModalResDTOVariant = typeof FeedbackModalResDTOVariant[keyof typeof FeedbackModalResDTOVariant];


export const FeedbackModalResDTOVariant = {
  REWARD_AVAILABLE: 'REWARD_AVAILABLE',
  REWARDED: 'REWARDED',
} as const;
