/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type GeneratePortfolioResDTOPortfolioStatus = typeof GeneratePortfolioResDTOPortfolioStatus[keyof typeof GeneratePortfolioResDTOPortfolioStatus];


export const GeneratePortfolioResDTOPortfolioStatus = {
  not_started: 'not_started',
  generating: 'generating',
  completed: 'completed',
  failed: 'failed',
} as const;
