/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type GeneratePortfolioResDTOExperienceStatus = typeof GeneratePortfolioResDTOExperienceStatus[keyof typeof GeneratePortfolioResDTOExperienceStatus];


export const GeneratePortfolioResDTOExperienceStatus = {
  ON_CHAT: 'ON_CHAT',
  GENERATE: 'GENERATE',
  DONE: 'DONE',
} as const;
