/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InsightControllerSearchVector200Error } from './insightControllerSearchVector200Error';
import type { InsightLogResDTO } from './insightLogResDTO';

export type InsightControllerSearchVector200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: InsightControllerSearchVector200Error;
  result?: InsightLogResDTO[];
};
