/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InsightSummaryResDTO } from './insightSummaryResDTO';

export interface InsightTurnHistoryItemResDTO {
  /** 턴 번호 */
  turnNumber: number;
  /** 사용자 메시지 */
  userMessage: string;
  /**
   * 언급된 인사이트 ID
   * @nullable
   */
  mentionedInsight: string | null;
  /** 이 턴에서 사용된 인사이트 목록 */
  insights: InsightSummaryResDTO[];
}
