/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedInsightLogResDTO } from './deletedInsightLogResDTO';
import type { InsightControllerDeleteLog200Error } from './insightControllerDeleteLog200Error';

export type InsightControllerDeleteLog200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: InsightControllerDeleteLog200Error;
  result?: DeletedInsightLogResDTO;
};
