/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InsightControllerUpdateLog200Error } from './insightControllerUpdateLog200Error';
import type { InsightLogResDTO } from './insightLogResDTO';

export type InsightControllerUpdateLog200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: InsightControllerUpdateLog200Error;
  result?: InsightLogResDTO;
};
