/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InsightControllerGetSimpleLogs200Error } from './insightControllerGetSimpleLogs200Error';
import type { SummaryLogResDTO } from './summaryLogResDTO';

export type InsightControllerGetSimpleLogs200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: InsightControllerGetSimpleLogs200Error;
  result?: SummaryLogResDTO[];
};
