/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InternalTemplateSectionResDTOAnchorSlotId } from './internalTemplateSectionResDTOAnchorSlotId';
import type { InternalTemplateSlotResDTO } from './internalTemplateSlotResDTO';
import type { InternalTemplateSubTemplateResDTO } from './internalTemplateSubTemplateResDTO';

export interface InternalTemplateSectionResDTO {
  sectionId: string;
  label: string;
  /** @nullable */
  anchorSlotId?: InternalTemplateSectionResDTOAnchorSlotId;
  /** level 4 카테고리 슬롯 */
  slots: InternalTemplateSlotResDTO[];
  /** level 5 하위 템플릿 (없으면 빈 배열) */
  subTemplates: InternalTemplateSubTemplateResDTO[];
}
