/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InsightTurnHistoryItemResDTO } from './insightTurnHistoryItemResDTO';
import type { InterviewMessageResDTO } from './interviewMessageResDTO';

export interface InterviewSessionStateResDTO {
  /** 현재까지의 인터뷰 메시지 목록 */
  messages: InterviewMessageResDTO[];
  /** 경험 정리 이름 */
  experienceName: string;
  /** 현재 인터뷰 단계 (1~n) */
  currentStage: number;
  /** 인터뷰 전 과정을 모두 완료했는지 여부 */
  allComplete: boolean;
  /** 현재 턴 번호 */
  turnNumber: number;
  /** 인사이트 멘션 턴 이력 */
  insightTurnHistory: InsightTurnHistoryItemResDTO[];
}
