/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InternalVisualizationSlideResDTOCurrentFills } from './internalVisualizationSlideResDTOCurrentFills';
import type { InternalVisualizationSlideResDTOGcsPreviewKey } from './internalVisualizationSlideResDTOGcsPreviewKey';
import type { InternalVisualizationSlideResDTOStatus } from './internalVisualizationSlideResDTOStatus';

export interface InternalVisualizationSlideResDTO {
  /** 슬라이드 UUID */
  id: string;
  /** 잡 UUID */
  jobId: string;
  slideOrder: number;
  sourceSlideId: string;
  slideFilename: string;
  status: InternalVisualizationSlideResDTOStatus;
  /** @nullable */
  currentFills: InternalVisualizationSlideResDTOCurrentFills;
  /** @nullable */
  gcsPreviewKey: InternalVisualizationSlideResDTOGcsPreviewKey;
  createdAt: string;
  updatedAt: string;
}
