/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface InterviewMessageResDTO {
  /** 메시지를 보낸 주체 (ai/human 등) */
  type: string;
  /** 메시지 본문 */
  content: string;
}
