/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InternalPortfolioDetailResDTOStatus } from './internalPortfolioDetailResDTOStatus';

export interface InternalPortfolioDetailResDTO {
  id: number;
  /** @nullable */
  sessionId: string | null;
  userId: number;
  experienceName: string;
  status: InternalPortfolioDetailResDTOStatus;
  description: string;
  responsibilities: string;
  problemSolving: string;
  learnings: string;
  /** @nullable */
  contributionRate: number | null;
}
