/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * RAG 파이프라인이 생성한 기업 분석
 * @nullable
 */
export type InternalCorrectionResDTOCompanyInsight = { [key: string]: unknown } | null;
