/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InternalInsightDetailResDTOCategory } from './internalInsightDetailResDTOCategory';
import type { InternalInsightDetailResDTOSimilarityScore } from './internalInsightDetailResDTOSimilarityScore';

export interface InternalInsightDetailResDTO {
  category: InternalInsightDetailResDTOCategory;
  /**
   * 코사인 유사도 (0~1, 1에 가까울수록 유사)
   * @nullable
   */
  similarityScore: InternalInsightDetailResDTOSimilarityScore;
  id: number;
  title: string;
  description: string;
  activityNames: string[];
}
