/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type InternalCorrectionResDTOStatus = typeof InternalCorrectionResDTOStatus[keyof typeof InternalCorrectionResDTOStatus];


export const InternalCorrectionResDTOStatus = {
  NOT_STARTED: 'NOT_STARTED',
  DOING_RAG: 'DOING_RAG',
  COMPANY_INSIGHT: 'COMPANY_INSIGHT',
  GENERATING: 'GENERATING',
  DONE: 'DONE',
  RAG_FAILED: 'RAG_FAILED',
  FAILED: 'FAILED',
} as const;
