/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { InternalControllerGetHealth200Error } from './internalControllerGetHealth200Error';
import type { InternalHealthResDTO } from './internalHealthResDTO';

export type InternalControllerGetHealth200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: InternalControllerGetHealth200Error;
  result?: InternalHealthResDTO;
};
