/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type InternalVisualizationJobResDTOPipelineStage = typeof InternalVisualizationJobResDTOPipelineStage[keyof typeof InternalVisualizationJobResDTOPipelineStage];


export const InternalVisualizationJobResDTOPipelineStage = {
  contentGenerating: 'contentGenerating',
  rendering: 'rendering',
  completed: 'completed',
} as const;
