/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface IssueTicketResDTO {
  /** HS256으로 서명된 티켓. sub/sid/iat/exp를 담는다. */
  ticket: string;
  /** 사용자의 AI 경험 정리 세션 id */
  session_id: string;
  /** 이번 턴의 request_id. 커밋 시 그대로 사용된다. */
  request_id: string;
  /** 티켓 만료까지 남은 초 */
  expires_in: number;
}
