/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface IssueTicketReqDTO {
  /** 재시도 시 실패한 요청의 request_id를 그대로 전달하면 새 UUID를 생성하지 않고 재사용합니다. */
  request_id?: string;
}
