/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 잡 이벤트 타입
 */
export type JobEventCallbackReqDTOEvent = typeof JobEventCallbackReqDTOEvent[keyof typeof JobEventCallbackReqDTOEvent];


export const JobEventCallbackReqDTOEvent = {
  pipeline_stage_changed: 'pipeline_stage_changed',
  all_completed: 'all_completed',
} as const;
