/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { JobSearchControllerGetNextValueBalanceQuestion200Error } from './jobSearchControllerGetNextValueBalanceQuestion200Error';
import type { ValueBalanceQuestionResDTO } from './valueBalanceQuestionResDTO';

export type JobSearchControllerGetNextValueBalanceQuestion200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: JobSearchControllerGetNextValueBalanceQuestion200Error;
  result?: ValueBalanceQuestionResDTO;
};
