/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface KakaoLinkAuthorizeResDTO {
  /** 카카오 계정 연결 동의 페이지 URL */
  authorize_url: string;
}
