/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface LinkKakaoChannelReqDTO {
  /**
   * 카카오 연결 콜백에서 발급한 연결 전용 토큰
   * @maxLength 4096
   */
  link_token: string;
}
