/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentControllerCreatePayment200Error } from './paymentControllerCreatePayment200Error';
import type { PaymentResDTO } from './paymentResDTO';

export type PaymentControllerCreatePayment200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: PaymentControllerCreatePayment200Error;
  result?: PaymentResDTO;
};
