/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface PdfExtractionProblemSolvingReqDTO {
  /**
   * 문제해결 항목 번호
   * @minimum 1
   */
  no: number;
  /** 상황 원문 텍스트 */
  situation: string;
  /** 전략 원문 텍스트 */
  strategy: string;
  /** 선택 이유 원문 텍스트 */
  reason: string;
}
