/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CorrectionStatusResDTO } from './correctionStatusResDTO';
import type { PortfolioCorrectionControllerGetCorrectionStatus200Error } from './portfolioCorrectionControllerGetCorrectionStatus200Error';

export type PortfolioCorrectionControllerGetCorrectionStatus200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: PortfolioCorrectionControllerGetCorrectionStatus200Error;
  result?: CorrectionStatusResDTO;
};
