/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type PortfolioCorrectionControllerGetCorrectionsParams = {
/**
 * 제목 기준 검색 키워드
 */
keyword?: string;
};
