/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CorrectionResDTO } from './correctionResDTO';
import type { PortfolioCorrectionControllerUpdateCorrectionTitle200Error } from './portfolioCorrectionControllerUpdateCorrectionTitle200Error';

export type PortfolioCorrectionControllerUpdateCorrectionTitle200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: PortfolioCorrectionControllerUpdateCorrectionTitle200Error;
  result?: CorrectionResDTO;
};
