/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCorrectionResDTO } from './createCorrectionResDTO';
import type { PortfolioCorrectionControllerCreateCorrection200Error } from './portfolioCorrectionControllerCreateCorrection200Error';

export type PortfolioCorrectionControllerCreateCorrection200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: PortfolioCorrectionControllerCreateCorrection200Error;
  result?: CreateCorrectionResDTO;
};
