/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { CorrectionSelectionResDTO } from './correctionSelectionResDTO';
import type { PortfolioCorrectionControllerMapCorrectionWithPortfolios200Error } from './portfolioCorrectionControllerMapCorrectionWithPortfolios200Error';

export type PortfolioCorrectionControllerMapCorrectionWithPortfolios200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: PortfolioCorrectionControllerMapCorrectionWithPortfolios200Error;
  result?: CorrectionSelectionResDTO[];
};
