/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { PdfExtractionActivityReqDTO } from './pdfExtractionActivityReqDTO';
import type { SavePdfExtractionResultReqDTOStatus } from './savePdfExtractionResultReqDTOStatus';

export interface SavePdfExtractionResultReqDTO {
  /** PDF 구조화 처리 상태(completed/failed) */
  status: SavePdfExtractionResultReqDTOStatus;
  /** 성공 시 source 타입 (현재 검증하지 않음) */
  sourceType?: string;
  /** 성공 시 추출된 활동 블록 배열 */
  activities?: PdfExtractionActivityReqDTO[];
  /**
   * 실패 사유 메시지
   * @maxLength 400
   */
  errorMessage?: string;
}
