/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface ScoredJobResDTO {
  code: string;
  name: string;
  /** 적합도(%) */
  matchRate: number;
  summary: string;
  coreSkills: string[];
  recommendedActivities: string[];
}
