/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * LLM 채워넣기 결과 (ready 이벤트 시 필수)
 */
export type SlideEventCallbackReqDTOCurrentFills = { [key: string]: unknown };
