/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface StreamRetrieverInsightDTO {
  /** 인사이트 ID (문자열) */
  id: string;
  title: string;
  activity_name: string;
  category: string;
  content: string;
  /** @nullable */
  similarity_score: number | null;
  /** 검색 소스 (mention | rag 등) */
  source: string;
}
