/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitFeedbackResponseReqDTOAnswers } from './submitFeedbackResponseReqDTOAnswers';

export interface SubmitFeedbackResponseReqDTO {
  /** @minimum 1 */
  formId: number;
  /** @minimum 1 */
  eventId: number;
  answers: SubmitFeedbackResponseReqDTOAnswers;
}
