/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 카테고리명
 */
export type SummaryLogResDTOCategory = typeof SummaryLogResDTOCategory[keyof typeof SummaryLogResDTOCategory];


export const SummaryLogResDTOCategory = {
  대인관계: '대인관계',
  문제해결: '문제해결',
  학습: '학습',
  레퍼런스: '레퍼런스',
  기타: '기타',
} as const;
