/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { ExpiringTicketTypeResDTO } from './expiringTicketTypeResDTO';

export interface TicketExpiringResDTO {
  /** 경험 정리 이용권 만료 예정 정보 */
  experience: ExpiringTicketTypeResDTO;
  /** 포트폴리오 첨삭 이용권 만료 예정 정보 */
  portfolioCorrection: ExpiringTicketTypeResDTO;
}
