/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export type TicketGrantRewardItemResDTOType = typeof TicketGrantRewardItemResDTOType[keyof typeof TicketGrantRewardItemResDTOType];


export const TicketGrantRewardItemResDTOType = {
  EXPERIENCE: 'EXPERIENCE',
  PORTFOLIO_CORRECTION: 'PORTFOLIO_CORRECTION',
} as const;
