/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { TicketGrantRewardItemResDTO } from './ticketGrantRewardItemResDTO';

export interface TicketGrantNoticePayloadResDTO {
  /** @nullable */
  displayReason?: string | null;
  rewards?: TicketGrantRewardItemResDTO[];
}
