/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface TraitAnswerReqDTO {
  /**
   * 문항 번호 (1~15)
   * @minimum 1
   */
  questionNo: number;
  /** 응답 값 (1~6). "그렇다"=6(해당 특성이 강함), "그렇지 않다"=1 */
  value: number;
}
