/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserNameReqDTO {
  /**
   * 변경하고자 하는 닉네임을 입력합니다.
   * @minLength 1
   * @maxLength 25
   */
  name: string;
}
