/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCorrectionStatusReqDTOStatus } from './updateCorrectionStatusReqDTOStatus';

export interface UpdateCorrectionStatusReqDTO {
  /** 변경할 상태값 */
  status: UpdateCorrectionStatusReqDTOStatus;
}
