/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePortfolioResultReqDTOStatus } from './updatePortfolioResultReqDTOStatus';

export interface UpdatePortfolioResultReqDTO {
  status: UpdatePortfolioResultReqDTOStatus;
  description?: string;
  responsibilities?: string;
  problemSolving?: string;
  learnings?: string;
  errorMessage?: string;
}
