/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { TicketGrantNoticeResDTO } from './ticketGrantNoticeResDTO';
import type { UserControllerMarkTicketGrantNoticeDismissed200Error } from './userControllerMarkTicketGrantNoticeDismissed200Error';

export type UserControllerMarkTicketGrantNoticeDismissed200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: UserControllerMarkTicketGrantNoticeDismissed200Error;
  result?: TicketGrantNoticeResDTO;
};
