/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { TicketBalanceResDTO } from './ticketBalanceResDTO';
import type { UserControllerGetTicketBalance200Error } from './userControllerGetTicketBalance200Error';

export type UserControllerGetTicketBalance200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: UserControllerGetTicketBalance200Error;
  result?: TicketBalanceResDTO;
};
