/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { AgreeTermsResDTO } from './agreeTermsResDTO';
import type { UserControllerAgreeTerms200Error } from './userControllerAgreeTerms200Error';

export type UserControllerAgreeTerms200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: UserControllerAgreeTerms200Error;
  result?: AgreeTermsResDTO;
};
