/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { TicketHistoryResDTO } from './ticketHistoryResDTO';
import type { UserControllerGetTicketHistory200Error } from './userControllerGetTicketHistory200Error';

export type UserControllerGetTicketHistory200 = {
  timestamp?: string;
  isSuccess?: boolean;
  /** @nullable */
  error?: UserControllerGetTicketHistory200Error;
  result?: TicketHistoryResDTO;
};
