/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사용자 전화번호
 * @nullable
 */
export type UserProfileResDTOPhoneNum = { [key: string]: unknown } | null;
