/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import type { VisualizationSlideItemResDTO } from './visualizationSlideItemResDTO';
import type { VisualizationSlidesResDTOBlockingReasons } from './visualizationSlidesResDTOBlockingReasons';
import type { VisualizationSlidesResDTOJobStatus } from './visualizationSlidesResDTOJobStatus';
import type { VisualizationSlidesResDTOPipelineStage } from './visualizationSlidesResDTOPipelineStage';

export interface VisualizationSlidesResDTO {
  jobStatus: VisualizationSlidesResDTOJobStatus;
  pipelineStage: VisualizationSlidesResDTOPipelineStage;
  canExport: boolean;
  blockingSlides: number[];
  blockingReasons: VisualizationSlidesResDTOBlockingReasons;
  remainingRegenerations: number;
  slides: VisualizationSlideItemResDTO[];
}
