/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Folioo API docs
 * API document of Folioo Development
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TicketControllerGetTicketProducts200
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 활성화된 이용권 상품 목록을 displayOrder 기준 오름차순으로 조회합니다. 할인율(discountRate)은 정가 대비 판매가로 계산됩니다.
 * @summary 이용권 상품 목록 조회
 */
export const ticketControllerGetTicketProducts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TicketControllerGetTicketProducts200>(
      {url: `/ticket-products`, method: 'GET', signal
    },
      options);
    }
  



export const getTicketControllerGetTicketProductsQueryKey = () => {
    return [
    `/ticket-products`
    ] as const;
    }

    
export const getTicketControllerGetTicketProductsQueryOptions = <TData = Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTicketControllerGetTicketProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>> = ({ signal }) => ticketControllerGetTicketProducts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TicketControllerGetTicketProductsQueryResult = NonNullable<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>>
export type TicketControllerGetTicketProductsQueryError = unknown


export function useTicketControllerGetTicketProducts<TData = Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerGetTicketProducts<TData = Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerGetTicketProducts<TData = Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 이용권 상품 목록 조회
 */

export function useTicketControllerGetTicketProducts<TData = Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTicketControllerGetTicketProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




